# Why is it difficult to stop?

All users feel something evil has possessed them. In the early days, it's a simple question of *“I will stop, just not today”*. Eventually we progress to believing we haven't got enough willpower to stop, or that there's something inherent in porn we must have in order to enjoy life. Porn addiction is like clawing our way out of a slippery pit: As we near the top, we see the sunshine, but find ourself sliding back down as our mood dips. Eventually we open our browser, and as we masturbate, we feel awful.

Ask a user, *“If you could go back to the time before you became hooked, with the knowledge you have now, would you have started using porn?”*

*“NO WAY!”* would be the reply.

Ask the confirmed user, someone who defends internet porn and doesn't believe it causes injury to the brain or downregulation of dopamine receptors: *“Do you encourage your children to use porn?”*

*“NO WAY!”* is again the reply.

Porn is an extraordinary enigma. As said previously, the problem isn't explaining why it's easy to stop, it's explaining why it's difficult to stop. The real problem is explaining why anyone does it *after* getting insights on neurological damage. Part of the reason we start is because of the other tens of millions already into it, yet all of these people wish they hadn't started in the first place, telling us it's like living life in second gear. We don't quite believe they're not enjoying it, as we associate it with freedom or being ‘sex-educated’, and work hard to become hooked ourselves. We then spend the rest of our lives telling others not to do it and trying to kick the habit ourselves, often thinking we're unique in this.

We also spend a significant proportion of our time feeling hopeless and miserable. ‘Educating’ ourselves with the supernormal makes us prefer and long for these cold images, even when warm, real ones are available. Through the constant surge and fall of dopamine induced by PMO, we sentence ourselves to a lifetime of isolation, irritability, anger, stress, fatigue, and sexual dysfunction. Using porn, with its absence of the best parts of sex and connection, we end up feeling miserable and guilty.

In fact, reading about internet pornography's addictive and destructive capabilities here and on other sites makes us even more nervous and hopeless! What sort of hobby is it that when you’re doing it, you wish you weren't, and when you aren't, you crave it? Users despise themselves every time they read about hypofrontality and desensitisation, every time they use behind their trusting partner's back, and every time they can't bring themselves to exercise after a daytime session. An otherwise intelligent and rational human being spends all their days in contempt. But worst of all, what do users get from having to endure life with these awful black shadows at the back of their mind? **Absolutely nothing!**

You might be thinking *“That's all very well, I know this, but once you’re hooked on these things it's very difficult to stop.”* But why is it so difficult? Some say it's because of the powerful withdrawal symptoms, but as you’ll soon come to learn, the actual withdrawal symptoms are very mild in fact. And this is evident when you consider that many PMOers have lived and died without realising they were addicts.

Some say internet porn is free and hence humankind should claim this biological bonanza, but this is untrue—it's addictive and acts just like any drug. Ask a user that swears they only enjoy ‘erotica’ like Playboy magazines if they've ever crossed the line to ‘unsafe porn’. And if they are completely honest, they would confess about the times they had rationalized crossing that line, rather than not use anything at all.

Enjoyment has nothing to do with it either. I enjoy crayfish, but I never got to the point where I had to have crayfish every day. With other things in life, we enjoy them while we’re doing them, but we don't sit around feeling deprived when we’re not.

Some say:  
*“It's educational!”* So how has it made you grow as a person?
*“It's sexual satisfaction!”* So why does it isolate you and make you feel insatiable cravings?
*“It's a feeling of release!”* Release from the stresses of real life? Ok, for an hour, before it all comes crashing back on you? And what stresses has it solved?
*“It helps me sleep”* So why can others sleep just fine without it? There are [many](https://www.sleepfoundation.org/insomnia/treatment/meditation) scientifically demonstrated [methods](https://www.sleepfoundation.org/insomnia/treatment/cognitive-behavioral-therapy-insomnia) to [fix](https://www.amazon.com/Uvex-Blocking-Computer-SCT-Orange-S1933X/dp/B000USRG90) sleep, and [more so](https://www.menshealth.com.au/what-is-the-military-method-the-technique-that-promises-to-help-you-sleep-in-2-minutes).

Many believe that porn relieves boredom, but boredom is a frame of mind. Porn will habituate you to novelty-seeking in no time, causing you to become increasingly bored until you finally participate in that wild-goose chase for just the right clip, becoming increasingly wired to seek anything that evokes novelty, strong emotion, and eventually, outrageous shock value.

Some say they only do it because their friends and everyone they know does it. If so, pray that your friends don't start cutting their heads off to cure a headache! Most users who think about it come to conclude that it's just a habit. This is not really an explanation, but having discounted all the usual, rational explanations, it appears to be the only remaining excuse. Unfortunately, it's equally illogical. Every day of our lives we change habits, some of them very enjoyable. We've been brainwashed to believe that PMO is a habit and that habits are difficult to break.

Are habits difficult to break? Drivers in the US are in the habit of driving on the right hand side of the road, yet when travelling overseas they break the habit with hardly any aggravation whatsoever. And when you get a new job you take on a different routine, so your habits change. These may take some getting used to, but it is nothing like breaking a life long struggle with porn addiction. We make and break habits every day of our lives, so why do we find it difficult to break a habit that makes us feel deprived when we don't have it, guilty when we do, one that we would love to break anyway, when all we have to do is *stop doing it?*

The answer is that porn isn't habit, *it's addiction!* That's why it appears to be so difficult to ‘give up’. Most users don't understand addiction and believe that they get some genuine pleasure or crutch from porn. They believe they’re making a genuine sacrifice if they quit.

The beautiful truth is that once you understand the true nature of porn addiction and the reasons why you use it, you’ll stop doing it, just like that. Within three weeks, the only mystery will be why you found it necessary to use porn as long as you have and why you can't persuade other users *how nice it is to not be a PMOer!*

## The Sinister Trap

Internet porn is a subtle and sinister trap that man and nature have combined to devise. Some of us are even warned about the dangers, but we can't believe how we aren't enjoying it. But what gets us into it in the first place? Typically it's free samples from amateurs and professionals who share. That's how the trap is sprung. If instead it warned us of the dangers of what we were getting into before even making that first peek, then the alarm bells would scream.

But these bells don't scream. Perhaps it's the shocking nature of many clips that reassures our young minds we’ll never become hooked, thinking because we don't enjoy them, we can stop whenever we want to. Or maybe the seeming innocence of soft material doesn't trigger any alarm bells, much like a skillful weavings that a con artist can play to direct our mind. As intelligent human beings, we'd then understand why half the adult population was systematically addicted to something cutting down our very potential to perform what we're viewing. Curiosity brings us closer to the doorstep of addiction, but we don't dare to click on the thumbnails we're glancing at, fearing they'd make us ill or send us down into a perilous and immoral pathway. And if we accidentally clicked on one, often our only desire is to get away from the page as soon as possible, while at the same time desperately curious even more.

Once this process has started, we are trapped. From now on we spend the rest of our lives trying to understand why we do it, telling our children not to start, and at odd times trying to escape ourselves. The trap is designed such that we try and stop only due to an ‘incident’, whether sexual performance, loss of a career or relationship, shortage of drive or just plain feeling like a leper. As soon as we stop, we have more stress due to withdrawal pangs, and with the method we relied on to remove that stress now unavailable.

Our resolve for quitting then proves to be shaky. After a few days of torture we convince ourselves that we've picked the wrong time to quit, deciding we’ll wait for periods without stress, which upon arriving removes our reason for initially stopping. Of course, that period will never arrive fully, and we begin to believe that our lives tend to become more and more stressful. We leave the protection of our parents, and the stresses of work, homemaking, mortgages, buying shelter, and raising children begins to crowd our lives. But this is an illusion. The most stressful parts of any creature's life are actually early childhood and adolescence.

We tend to confuse responsibility and stress. A user's life — like a drug addict's — automatically becomes more stressful because porn doesn't relax us or relieve stress, as some try to make us believe. It's just the reverse, causing us to become more stressed as we continue using, with every guilt laden late night aftermath piling more straw onto the camel's back. Even users who kick the habit — as most do one or more times throughout their lives — can lead perfectly happy lives yet suddenly become hooked again. Wandering into the pornographic maze, our minds become hazy and we spend the rest of our lives trying to escape. Many do succeed, only to fall into the sinister trap at a later date.

Solving the problem of porn addiction is a riddle. It is complex and difficult. But once you see the answer, it's simple and fun, and you wonder why you didn't think of that! EasyPeasy contains the solution to this puzzle, leading you out of the maze, never wandering in again. **All you have to do is follow every instruction to the letter**. However, if you take **a wrong turn by jumping chapters**, or **blazing through the book at lightning speed** without carefully making a deliberate effort on your first time reading, then the rest of the instructions are pointless.

Anyone can find it easy to stop, but we must first establish the facts. No, not facts designed to scare you, there's already more than enough information out there. If that was going to stop you, you'd have already stopped. But why do we find it difficult to stop? Answering this requires us to know the real reason we’re still using porn, boiling down to two factors. They are:

-   Nature and internet porn.

-   Societal brainwashing.

Porn users are intelligent, rational human beings. They know they’re taking enormous future risks so they spend lots of time rationalising their ‘habit’. But porn users in their hearts know they’re fools, knowing they had no need to use porn before becoming hooked. Most remember that their first ‘peek’ was a mix of revulsion and novel curiosity. They then specialise in locating, filtering and bookmarking sites, working hard to become hooked.

Most annoyingly, there's the sense that non-addicts — most women, older guys, and people living in countries where high-speed internet porn is unavailable — aren't missing out on anything and find the situation laughable. By dismantling these factors in the next chapters, you too will understand the sinister trap!

