# Saving Time

Usually when users try stopping, the main reasons given are health, religion and partner stigma. Part of the brainwashing of this awful drug is the sheer slavery of it; man has fought hard to abolish slavery in many parts of the world — yet the user spends life suffering self-imposed slavery. They’re oblivious to the fact that when they’re allowed to use porn they wish they were a non-user. The only time that porn becomes precious is when we’re ‘trying’ to cut down or abstain, or when abstinence is forced on us.

It cannot be repeated often enough that brainwashing makes it difficult to stop porn, so the more we dispel before we start, the easier you'll find it to achieve your goal. Confirmed users, who don't believe that porn has any negative effect on their health (porn-induced erectile dysfunction, hypofrontality, etc.) and aren't having a mental tug of war are typically younger or single with an occasional sex partner. Thus, the internal feedback is lost due to the nature of their youth or is too infrequent to be observed and registered.

A better argument for a younger user is the time spent, rather saying "*I can’t believe you aren’t worried about the time you are spending.*" Generally their eyes light up, feeling disadvantaged if attacked on health grounds or social stigma, but on time...  
"*Oh, I can afford it. It’s only* x *hours per week and I think it’s worth it, it’s my only vice of pleasure.*"

"*I still can’t believe you’re not worried. Let’s assume a half hour daily average which includes the physical drain of dopamine withdrawals, you’re spending approximately a full working day every fortnight. I’m sure you’d agree that half an hour a day is a very conservative estimate. Have you thought about how much time you’ll spend in your lifetime? What are you doing in that time? Developing real relationships? No, your favorite porn star doesn’t have sympathy for you, just because you spent so much time on their videos — you’re throwing time away! Not only that, you’re actually using that time to ruin your physical health, destroying your nerves and confidence in order to suffer a lifetime of slavery, pain, melancholy and peevishness. Surely that must worry you, right?*"

It's apparent at this point — especially with younger users — that they've never considered it a lifetime addiction. Occasionally, they work out the time they waste in a week and that's alarming enough. Very occasionally, and only when they think of stopping, they’ll estimate what they spend in a year which is frightening — but over a lifetime is unthinkable. However, because we’re in an argument the confirmed user will impulsively say, *“I can afford it, it’s only so much a week"*, pulling an encyclopedia salesman routine on themselves.

Would you refuse a job offer which pays your current annual salary and also gives you a month off every year? Any user would sign in a heartbeat and would get busy finding holiday deals to exotic locations. Figuring out how to spend a full month with no work would be the biggest problem to solve. In every discussion with a confirmed user (and please bear in mind that's not someone like yourself who plans to stop) nobody has ever taken me up on that offer. Why not?

Often at this point, a confirmed user will say, "*Look, I’m not really worried about the money aspect.*" If you’re thinking along those lines ask yourself why you aren't worried. Why in other aspects of your life will you go to great deals of trouble to save a few dollars here and there, but spend thousands killing your happiness and hanging the expense?

Every other decision you make in your life will be the result of an analytical process of weighing up advantages and disadvantages to arrive at a rational decision. It may be the wrong decision, but it’ll be the result of rational deduction. Whenever any user weighs up the pros and cons of using internet porn, the answer is a dozen times over, **"STOP USING! YOU’RE A MUG!"** Therefore, all users are using not because they want or decide to, but because they can't stop. They ***have*** to use porn, and so brainwash themselves, keeping their heads in the sand.

Confirmed users should keep in mind that the situation will only get exponentially worse, with more studies coming out and more people talking about the ill effects of internet porn. Today, it's non-medical people discussing the effects, tomorrow it’ll be on your doctor's list of diagnostic tests. Gone are the days where the user can hide ‘downtime’ behind work stress in their sex life; your partner is going to ask why you’re on your laptop late at night. The poor user — already feeling wretched — now wants the ground to open up and swallow them.

The strange thing is that though many people would pay good money for gym memberships and personal trainers to build muscles and look sculpted (and many of them in their imaginary (and real) desperation turn to treatments such as boosting testosterone, with dubious and dangerous side effects), there are many people in this group who would benefit from stopping a practice systematically destroying their brain's natural relaxation systems.

This is because they’re still thinking with the brainwashed mind of the user. Wipe the sand out of your eyes for a moment. Internet porn is a chain reaction and a chain for life, and if you don't break that chain you’ll remain a user for the rest of your life. Estimate how much time you think you’ll spend on porn for the remainder of your existence. Obviously the amount will vary from person to person, but let's assume it's a year and a half of work hours. Imagine if there were a cheque from the lottery for a year and a half of your salary lying on your carpet tomorrow? You'd be dancing with delight, so start dancing! You’re about to start receiving those benefits!

If you think this is a tricky way of seeing it, you’re still kidding yourself. Work out how much time you would have saved if you'd never taken your first peek right at the very start.

Shortly, you’ll be making the decision to use your final session (not yet, please remember the instructions!), remaining a non-user by not falling for the trap again. All you have to do to remain a non-user is not using porn and avoiding ‘just one peek’. Remember if you do, it’ll cost you whatever you estimated your salary gain will be.

If you’re mentoring someone for their porn addiction, tell them they know someone who's refused a job offer that pays their current annual salary and also gives them a full month's worth of paid time off. When asked who that idiot is tell them, ***"You!"*** It's rude, but sometimes you need to get the point across in a less than polite way.
