# The Willpower Method

It's an accepted fact in society that it's very difficult to stop porn. Books and forums advising you on how to stop usually start off by telling you how difficult it is. The truth is that it's ridiculously easy. It's understandable to question that statement, but first just consider it. If your aim is running a mile in four minutes, *that's* difficult and you’ll have to undergo years of hard training, and even then possibly being physically incapable.

However, all you have to do to stop porn is to not watch it and/or masturbate anymore. Nobody forces you to masturbate (apart from yourself) and unlike food or water, it isn't needed for survival. So if you want to stop doing it, why should it be difficult? In fact, it isn't. It's users who make it difficult for themselves through use of willpower or any method that forces the user to feel like they’re making some sort of sacrifice. Let's consider these methods.

We don't decide to become users, we merely experiment with porn magazines or websites and because they’re awful (that's right, awful), apart from our desired clip, we’re convinced that we can stop whenever we want to. At first, we watch those first few clips when we want to and on special occasions. Before we realise it, we’re not only visiting those sites regularly and masturbating when we want to — we’re masturbating to them daily. Porn has become a part of our lives, ensuring we require an internet connection wherever we go. We then believe we’re entitled to love, sex, orgasm and the stress-relieving properties of porn. It doesn't seem to occur to us that the same clip and actors don't provide us with the same degree of arousal and we begin fighting against the red line to avoid ‘bad porn’. In fact, masturbation and internet porn neither improves our sex lives nor reduces stress, it's merely that users believe they can't enjoy life or handle stress without it.

It usually takes a long time to realise that we’re hooked because we suffer from the illusion that users watch porn because they enjoy it — and not because they ***need*** to. When we’re not ‘enjoying' porn, which we can never do unless novelty, shock or escalation is added, we’re under the illusion we can stop whenever. This is a confidence trap. “*I don’t enjoy porn, so I can stop when I want to*". Only you never seem to ‘want’ to stop.

It's usually not until we actually try to stop that we realise a problem exists. The first attempts are generally early — triggered by meeting a partner and noticing they aren't ‘quite enough’ after the initial dates. Another common reason is noticing health effects present in daily life.

Regardless of reason, the user always waits for a stressful situation, whether health or sex. As soon as they stop, the little monster begins to get hungry. The user then wants something to pump their dopamine, such as cigarettes, alcohol, or their favourite — internet porn — with their harem only a click away. The porn cache is no longer in the basement, it's virtual and accessible from anywhere. If their partner is around or they’re with friends, they no longer have access to their virtual harem, making them even more distressed.

If the user has come across scientific material or online communities, they’ll be having a tug-of-war in their mind, resisting temptations and feeling deprived. Their way to usually relieve stress is now unavailable, suffering a triple blow. The probable result after this period of torture is compromise – “*I’ll cut down*" or “*I’ve picked the wrong time*" or perhaps, “*I’ll wait until the stress has gone from my life.*" However, once the stress has gone there's no reason to stop and the user doesn't decide to quit again until the next stressful time.

Of course, there's never a right time because life for most people becomes more stressful. We leave the protection of our parents, entering the world of setting up home, taking on mortgages, having children and having more responsible jobs. Regardless — the user's life cannot become less stressful because porn actually causes stress. The quicker the user passes on to the escalation stage, the more distressed they become and the greater the illusion of dependency grows.

In fact, it's an illusion that life becomes more stressful and porn — or a similar crutch — creates that illusion. This will be discussed in greater detail later, but after these initial failures the user usually relies on the possibility that one day they’ll wake up and just not want to masturbate or use porn. This hope is usually kindled by stories heard from other ex-users, “*I wasn't serious until I had a fading penetration, then I didn’t want to use porn anymore and stopped masturbating.*"

Don't kid yourself, probe these rumours and you’ll discover they’re never quite as simple as they appear. Usually the user has already been preparing to stop and merely used the incident as a springboard. More often in the case of people who stop “just like that," they've suffered a shock: perhaps a discovery by their partner, a self-spotting incident of accessing porn not of their normal sexual orientation or they've had a sexual dysfunction scare themselves. “*That’s just the sort of person I am.*" Stop kidding yourself. It won't happen unless you make it happen.

Let's consider in greater detail why the willpower method is so difficult. For most of our lives we adopt the head-in-the-sand, “*I’ll stop tomorrow*" approach. At odd times, something will trigger off an attempt to stop. It may be concerns about health, virility or a bout of self-analysis and realising we don't actually enjoy it. Whatever the reason, we start to weigh up the pros and cons of porn. Sex is split into tantric (touch, smell, voice) and propagative (orgasm); this is one of the major keys in opening our mind, and without this important distinction, there’ll be confusion, which leads to failure. On rational assessment we find out what we've known our entire lives, the conclusion is a thousand times over “***STOP WATCHING IT!***"

If you were to sit down and give points to the advantages of stopping and compare them to the advantages of porn, the total point count for stopping would far outweigh any ‘disadvantages'. If you employ Pascal's Wager, by quitting you’re losing almost nothing, with high chances of gains and higher chances of *not* losing. Although the user knows that they’ll be better off as a non-user, the belief they're making a sacrifice trips them up. Although an illusion, it's powerful. They don't know why, but the user has the belief that during the good and bad times of life, the sessions appear to help. Even before starting their attempt, societal brainwashing further reinforced by the brainwashing from their own addiction is then combined with the even more powerful brainwashing of how difficult it is to ‘give up’.

Users hear stories of those who've stopped for many months and still desperately crave it, or of disgruntled quitters, who, having stopped, spend the rest of their lives bemoaning the fact that they'd love to have a session. There are tales of users stopping for many months or years, living happy lives, only to have one ‘peek’ at porn and are suddenly hooked again. Users probably know several in the advanced stages of the disease, visibly destroying themselves and clearly not enjoying life — yet continuing to use. Additionally, they've probably suffered one or more of those experiences themselves.

So instead of starting with the feeling, “*Great! Have you heard the news? I don’t need to watch porn any more!*", they start instead with feelings of doom and gloom — as if trying to climb Everest — and they falsely determine that once the little monster has its hooks into you, you’re hooked for life. Many users start the attempt by apologising to their girlfriends or wives, “*Look, I’m trying to give up porn. I’ll probably be irritable for the next couple of weeks, so try to bear with me.*" Most attempts are doomed before they begin.

Assume that the user survives a few days without a session. They’re getting back their arousal and are starting to recover. They haven't opened their favourite tube sites and are consequently getting aroused by normal stimuli they'd previously zoned out at. The reasons they decided to stop in the first place are rapidly disappearing from their thoughts, like seeing a bad road accident whilst driving. It'll slow you down for a while, but you stomp your foot on the throttle the next time you’re late for an appointment.

On the other side of the war is the little monster who still hasn't had its fix. There's no physical pain — if you had the same feeling because of a cold, you wouldn't stop working or get depressed, you'd laugh it off. All the user knows is they want to visit their harem. The little monster knows this, and starts up the big brainwashing monster, causing the same person who was a few hours or days earlier listing all of the reasons to stop, to now desperately search for any excuse to start again. They begin saying things like:

-   “*Life is too short, a bomb could go off, I could step under a bus tomorrow. I’ve left it too late. They tell you everything gives you an addiction nowadays.*"

-   “*I've picked the wrong time.*"

-   “*I should have waited until after Christmas, after my holidays/tests, after this stressful event in my life.*"

-   “*I can’t concentrate, I’m getting irritable and bad-tempered, I can’t even do my job properly.*"

-   “*My family and friends won’t love me. Let’s face it, for everybody’s sake I have to start again. I’m a confirmed sex addict and there’s no way I’ll ever be happy again without an orgasm.*"

-   “*Nobody can survive without sex.*" (Brainwashed by well meaning people who don't consider the distinction between the tantric and propagative parts of sex).

-   “*I knew this would happen, my brain is ‘sensitised’ by DeltaFosB due to changes affected by dopamine surges because of my past excessive porn use. Sensitisation can ‘never’ be removed from the brain.*"

At this stage, the user usually gives in. Firing up the browser, the schizophrenia increases. On one hand there's the tremendous relief of ending the craving as the little monster finally gets its fix; on the other hand, the orgasm is awful and the user cannot understand why they’re doing it. This is why the user thinks they lack willpower. It's not in fact lack of willpower, all they've done is to change their mind and make a perfectly rational decision in light of the latest information.

"*What’s the point of being healthy or rich if you’re miserable?*"

Absolutely none! Far better to have a shorter enjoyable life than a lengthy miserable one. Fortunately, this is untrue for the non-user, as life is infinitely more enjoyable. The misery the user is suffering isn't due to withdrawal pangs — though it's initially triggered by them — the actual agony is the tug-of-war in the mind caused by doubt and uncertainty. Because the user starts by feeling they’re making a sacrifice, they then begin to feel deprived, which is a form of stress.

One of these stressful times is when the brain tells them to ‘have a peek’, wanting to backtrack as soon as they stop. But because they've stopped, they can't and this makes them even more depressed and sets the trigger off again. Another factor making quitting so difficult is waiting for something to happen. If your objective is passing a driving test, as soon as you've passed the test it's certain whether you've achieved your objective. Under the willpower method the internal narrative is – “*If I can go long enough without internet porn, the urge to watch it will eventually go.*" You can see this in practice in online forums where addicts talk about their streaks or days of abstinence.

As said above, the agony the user undergoes is mental and caused by uncertainty. Although there's no physical pain, it still has powerful effects. Now miserable and insecure, the user is far from forgetting, now full of doubts and fears.

-   “*How long will the craving last?*"

-   “*Will I ever be happy again?*"

-   “*Will I ever want to get up in the morning?*"

-   “*How will I ever cope with stress in future?*"

The user is waiting for things to improve but while they’re still moping, the ‘harem’ is becoming ever more precious. In fact, something *is* happening but unconsciously, if they can survive weeks without opening the browser, the craving for the little monster disappears. However, as stated previously the pangs of withdrawal from dopamine and opioids are so mild that the user isn't even aware of them. At this time, many users sense they've ‘kicked it’ and so take a peek to prove it, sending them back down the water slide. Having supplied dopamine to the body, there's now a little voice at the back of their mind saying “*You want another one.*" In fact, they'd kicked it, but have hooked themselves again.

As a child you watched cartoons and as per neuroscience you formed neural pathways (DeltaFosB) for them. If you wanted to discourage a child from watching, you'd study if those pathways still existed and survey adults on why they don't like to watch their favourite childhood cartoons anymore. For one, there's better entertainment available and secondly, the cartoons just don't hold the magic anymore. With the willpower method you’re just denying the child the cartoon, but with EasyPeasy you’re also making sure they see no value in it. Which is better?

The user won't usually get into another session immediately, thinking “*I don’t want to get hooked again!*" and allows a safe period of hours, days or even weeks to pass. The ex-user can then say, “*Well, I didn’t get hooked, so I can safely have another session.*" They've fallen back into the same trap as when they first started and are already on the slippery slope.

Users who succeed using the willpower method tend to find it long and difficult because the primary problem is the brainwashing. Long after the physical addiction has died, the user is still moping around, miserable. Eventually, after surviving this long term torture, it begins to dawn on them that they aren't going to give in, stopping the moping and accepting that life goes on and is enjoyable without porn. There are significantly more failures than successes, because some who succeed go through their lives in a vulnerable state, left with a certain amount of brainwashing telling them that porn does in fact give them a boost. This explains why many users who've stopped for long periods end up starting again later on.

Many ex-users will have the occasional session as a ‘special treat’ or to convince themselves how strong their self-control is. It does exactly that — but as soon as their session ends the dopamine starts to leave and a little voice at the back of their mind begins driving them towards another one. If they decide to partake, it still seems to be under control, no shocks, escalation or novelty-seeking, so they say, “*Marvellous! While I’m not really enjoying it, I won’t get hooked. After Christmas / this holiday / this trauma, I’ll stop.*" Little do they know that the water slides of their brain have been greased even more.

Too late, they’re already hooked! The trap they managed to claw themselves out of has claimed its victim again.

As said previously, enjoyment doesn't come into it. It never did! If we watched because of enjoyment, nobody would stay on the tube sites for longer than it takes to finish the deed. Regardless, a better way to self-pleasure is from memories. We assume we enjoy internet porn only because we can't believe we'd be stupid enough to get addicted if we didn't enjoy it. Most users don't have any idea about supernormal stimulus, novelty or shock-seeking and even after reading about it, they don't believe their use is motivated by evolutionary reward-circuit wiring. That's why so much of porn is subconscious — if you were aware of the neurological changes and had to justify it costing you money in the future, even the illusion of enjoyment would go.

When we try to block our minds to the bad side, we feel stupid. If we had to face it, that would be intolerable! If you watch a user in action, you’ll see they’re happy only when unaware they’re using. Once aware, they tend to be uncomfortable and apologetic. Porn feeds the little monster so upon purging it from your body along with the brainwashing (big monster), you’ll have neither need nor desire to watch!
