# Timing

Apart from the obvious point that it's doing you no good and that now is the right time to stop, timing is important. Society treats internet porn flippantly as a slightly distasteful habit that doesn't injure your health. This is untrue. It's drug addiction, a disease and destroyer of relationships in society. The worst thing that happens in most users' lives is getting hooked on this awful addiction. If they stay hooked, horrendous things happen. Timing is therefore important to give yourself the right to a proper cure.

Firstly, identify the times or occasions when porn appears to be important to you. If you're a businessperson who uses it for the illusion of stress relief — pick a relatively slack period or a holiday. If you use porn mainly during boring or relaxing periods, the opposite applies. Regardless, take the attempt seriously and make it the most important thing in your life.

Look ahead for a period of three weeks and try to anticipate any event that might lead to failure. Occasions like conference trips, your partner being out of town, etc., need not deter you, provided you anticipate them in advance and don't feel that you'll be deprived. Don't attempt to cut down in the meantime, as this will only create the illusion that being denied is enjoyable. In fact, it helps to force yourself to watch and have as many porn sessions as possible. While you're having the last session and your last time, be mindful of the disappointment due to satiation, unfulfilled expectations, any bodily pain, withdrawal effects, peevishness and melancholy. Think of how marvellous it'll be when you allow yourself to stop doing it.

**WHATEVER YOU DO, DON'T FALL INTO THE TRAP OF JUST SAYING, "NOT NOW, LATER" AND PUTTING IT OUT OF YOUR MIND. WORK OUT YOUR TIMETABLE NOW AND LOOK FORWARD TO IT.**

Remember, *you aren't giving anything up*. On the contrary, you're about to receive marvellous positive gains.

For years, the medical profession has viewed porn as harmless without knowing the difference between the tame static porn of yesteryear and the latest virtual reality streaming experience. The problem is that although every user consumes internet porn purely to relieve the dopamine craving caused by it, it's not the addiction to the chemical that hooks the user, but self-brainwashing resulting from addiction. An intelligent person will fall for a confidence trick, but only a fool would continue falling for it upon realising the trick. Fortunately, most users aren't fools, they only think they are. Each individual user has their own private brainwashing. That's why there appears to be such a diverse range of types of addicts, only serving to further compound the mysteries.

While the benefit of the original book was to quit nicotine (one of the quickest and most addictive drugs known to man), it was agreeably surprising to realise that the philosophy propounded in the original book is still sound when adapted. The accumulated knowledge and challenge that Carr and myself undertake is how to communicate that knowledge to each individual user. The fact I know every user can not only find it easy to stop, but can actually enjoy the process, is not only pointless but exceedingly frustrating unless the user can be made to realise it. In his original book, Allen Carr explains his controversial advice:

>"Many people have said to me: *'You say, "Continue to smoke until you finish the book." This tends to make the smoker take ages to read the book or just not finish it. Period. Therefore, you should change the instruction.'* This sounds logical, but I know if the instruction were: *'Stop immediately'*, some smokers wouldn't even start reading the book. I had a smoker consult me in the early days. He said, *'I really resent having to seek your help, I know I'm strong-willed. In every other area of my life I'm in control. Why is it that all these other smokers quit by using their own willpower, yet I have to come to you?'* He continued, *'I think I could do it on my own, if I could smoke while I was doing it.'\"*

Societal belief dictates that stopping smoking is incredibly difficult, so what does a smoker need when something is difficult? Our little friend, our crutch. Escaping smoking appears to be a double-blow: not only is there a difficult task to perform — which is hard enough — but the crutch we normally rely on for such occasions isn't available. Perhaps the real beauty of this method is that you don't need to ‘give up' while going through the process. Instead, we get rid of all fears and doubts initially, so upon finishing the final session you're already enjoying freedom.

Therefore, this hackbook will keep the same advice intact. No matter how much it's said that it'll be easy and enjoyable, there'll be a vast majority who won't be able to accept it due to personal brainwashing on how difficult quitting is.

Timing is the only chapter that causes me to question Allen's original advice seriously. Above all, if triggers include office stress, then picking a holiday to make an attempt, and vice versa. This isn't the easiest way, instead picking what you consider to the most *difficult* time. Whether that's stress, social obligations, concentration or boredom, once you've proven you cope with and enjoy life in the worst situations, every other one is enjoyable. But if that were the advice, would you even make the attempt?

Here's an analogy. My sister and I intend to swim together. We arrive at the pool at the same time, but rarely end up swimming together. The reason being that she immerses one toe and half an hour later is actually swimming. That's slow torture. I know in advance that at some stage, no matter how cold the water is, I'll have to brave it at some point. So I've learned to do it the easy way: diving straight in. Now, imagine if I were in a position to insist that if she didn't dive straight in, she couldn't swim. If that were the case, she wouldn't swim at all. Do you see the problem?

From feedback, many users have used the original timing advice to delay what they think will be the ‘evil day'. My next thoughts were using a similar technique to the ‘advantages of porn' chapter, something like — *“Timing is very important and in the next chapter you'll be advised on the best time to make the attempt."* and on the next page there's just a massive *“NOW!"* That is in fact, the best advice, but would you take it? Perhaps the most subtle aspect of the trap is that when we have genuine stress in our lives, it's not the right time to stop, but at times without stress, we have no desire to end the torture. Ask yourself the following questions:

1.  When you got onto porn for the first time, did you really decide that you'd continue to depend on it for the rest of your life without ever being able to stop? ***Of course you didn't!***

2.  Are you going to continue the rest of your life without ever being able to stop? ***Of course you aren't!***

So when will you stop? Tomorrow? Next year? The year after? Isn't that what you've been asking yourself since you first realised you were hooked? Are you hoping that one morning you'll wake up and just not want to watch anymore? Stop kidding yourself, with any addiction you get progressively more hooked, not less. Are you going to wait until you've actually started to feel that getting out of bed is harder than just masturbating? That would be a bit pointless.

The real trap is the belief that now isn't the right time — it'll always be easier tomorrow. We believe that we live stressful lives, but in actuality we don't. Most genuine stress has been removed from our lives. When leaving home you don't live in fear of being attacked by wild animals, most don't wonder where their next meal will come from, or if a roof will be over their heads tonight. Think of the life of a wild animal, every time a rabbit comes out of its burrow, it's facing Vietnam for its entire life. But the rabbit handles it, it's got adrenaline and other hormones, and so do we. The truth is, the most stressful periods for any creature's life are early childhood and adolescence. But three billion years of natural selection has equipped us to cope with stress, and many who grow up with hard childhoods lead normal lives.

It's cliché to say, *“If you haven't got your health, you've got nothing"* but it's absolutely true. When you feel physically and mentally strong you can enjoy the highs and handle the lows. Many confuse responsibility with stress; responsibility only becomes stressful when we don't feel strong enough to handle it. What destroys most isn't stress, jobs or old age, but the illusory, lying crutches they turn to.

Look at it this way — you've already decided you aren't staying in the trap for the rest of your life. Therefore at some point — whether you find it easy or difficult — you'll have to go through the process of getting free. Porn isn't a habit or pleasure, it's drug addiction and a disease. We've established that far from being easier tomorrow, it'll get progressively worse. The time to get rid of it is **now** — or as near to now as you can manage. Just think of how quickly each week of our lives passes. That's all it takes. Think of how nice it'll be to enjoy the rest of your life without ever-increasing shadows hanging over you. Provided you follow all the instructions, you won't even have to wait five days or three weeks. You'll not only find it easy to quit, **You'll enjoy it!**
