# Will I miss the fun?

**No!** Once the little porn monster is dead, after your body stops craving dopamine, and the porn water slides in your brain rapidly begin to fade due to lack of 'greasing', any remaining brainwashing will vanish. Not only will you find yourself both physically and mentally better equipped to handle the stresses and strains of life, but you'll enjoy the good times to the fullest.

There's only one danger, that being the influence of those who still use sex as their crutch and pleasure. *'The other man's grass is always greener'* is commonplace in many aspects of our lives and easily understandable. Why in the case of porn — with disadvantages so enormous when compared to the illusionary ‘advantages' — does the ex-user tend to envy those demanding sex and pornography as a crutch?

With all of the brainwashing from childhood, it's quite understandable that we've fallen into the trap. Why is it then — after realising what a mug's game porn is, and managing to kick the habit — that we walk straight back into the same trap? It's the influence of the societal brainwashing conflating porn with sex, presented as normal. The ex-user has a pang! The insecure void feelings of them being single (which isn't a crime anyway) causes feelings of anxiety, and drives them to ride the water slide. This is indeed a curious anomaly, particularly if this observation is considered: not only is every non-user in the world happy to be so, but every user in the world even with their warped, addicted, brainwashed mind suffering the delusion of enjoyment or relaxation, wishes they'd never become hooked in the first place. So, why do some ex-users envy?

1.  ‘Just one peek.' Remember, it doesn't exist. Stop seeing the isolated occasion and start looking at it from the point of view of the porn user. You might be envying them, but they don't approve of themselves, and they envy you. If only you could somehow clinically watch another user, as they can be the most powerful boost of all to help you out of it. Notice how quickly they open many tabs and browser windows? Fast forwarding to the important sections, quickly getting bored of clips and running through the gamut of genres producing novelty, shock, anxiety, etc. Notice particularly that the act appears to be automatic. Remember — they aren't enjoying it, it's that they can't enjoy themselves without it. The next morning, waking up with a weakened will, lost energy and bleary eyes, they'll have to continue choking themselves at the first appearance of stress and strain. They're facing a lifetime of filth, poor mental health and stained confidence — a lifetime of destroying themselves with black shadows at the back of their mind. To achieve what purpose? The illusion you're getting what you ‘deserve' and damned pleasure?

2.  The second reason some ex-users have pangs is because the porn user is doing something - such as self-pleasuring - and the non-user isn't, so they tend to feel deprived. Get it clear in your mind, it's not the non-user who is being deprived, but the poor addict who is being deprived of:

    -   Health

    -   Energy

    -   Confidence

    -   Peace of mind

    -   Courage

    -   Tranquillity

    -   Freedom

    -   Self-respect

Get out of the habit of envying porn users and start seeing them as the miserable, pathetic creatures they really are. I know, I was once one of the worst. That's why you're reading this book and not the ones who can't face up to it and continue to kid themselves.

You wouldn't envy a heroin addict, and like all drug addiction, yours won't get any better. Each year it'll get exponentially worse — if you don't enjoy being a user today, you'll enjoy it even less tomorrow. Don't envy other users, pity them. Believe me: ***They need your pity!***
