# The Withdrawal Period

For up to three weeks after your last session you may be subjected to withdrawal pangs. These consist of two quite separate but distinct factors:

1.  Dopamine withdrawal pangs. An empty, insecure feeling similar to hunger, identified as cravings or a ‘something-I-must-do’ feeling.

2.  Psychological triggers of certain external stimuli such as commercials, online browsing, telephone conversations, etc.

Failure to understand and differentiate between these two distinct factors makes it difficult to achieve success using the willpower method, and is the reason why many who do end up falling into the trap again. Although the withdrawal pangs of dopamine don't cause physical pain, don't underestimate their power. We talk of ‘hunger pains’ if going without food for a day; there might be stomach rumbles, but there isn't any physical pain. Even so, hunger is a powerful force and we’re likely to become very irritable when deprived of food. It's similar to when our body is craving a dopamine rush, the difference being that our body needs food, not poison. With the right frame of mind, withdrawal pangs are easily overcome and disappear very quickly.

After abstaining for a few days on the willpower method, the craving for dopamine flushes soon disappears. It's the second factor — brainwashing — that causes difficulty. The user has gotten into the habit of relieving their withdrawal pangs at certain times and certain occasions, which causes an association of ideas (*“I’ve got a hard on, so I must watch porn."* or “*I’m in bed with my laptop and I must have a session to feel happy*"). The effect is best illustrated with an example: you have a car and the indicator is on the left, but on your next, it's on the right. You know it's on the left, but for a couple of weeks you turn the windscreen wipers on when you want to indicate.

Stopping is similar: during the early days the trigger mechanism will operate at certain times. You’ll think about wanting a session, so therefore countering the brainwashing is essential right from square one and will cause these cues and triggers to quickly disappear. Under the willpower method, because the user believes they’re making a sacrifice, they’re moping about it and waiting for urges to leave, the opposite of removing these trigger mechanisms, and actually ends up increasing them. Similarly, under guru thinking, the user starts to wonder when they’re going to become a god and even demands that they shouldn't have those thoughts, paving the way for self-loathing and failure.

A common trigger is alone time, particularly at social events with friends. The ex-user using other methods to quit is already miserable due to feeling deprived of their usual crutch or pleasure. Their friends are with their partners and acting intimate. The user is either single or not ‘getting any’ from their partner, and now no longer enjoys what should be a pleasant social occasion. Their existing brain water slides lead them to porn, which is easier than trying to woo their partner.

Because of the association of entitlement to sex with their well-being, they’re now suffering a triple blow and the brainwashing is actually increased. If they’re resolute and can hold out long enough, they eventually accept their lot and get on with their life. However, part of the brainwashing still remains, the second most pathetic aspect being the user having quit but even after several years still craves ‘just one last visit to the harem’ on certain occasions. They're pining for an illusion that exists only in their mind, and they needlessly torture themselves.

Even under EasyPeasy, responding to triggers is the most common failing. The ex-user tends to regard internet porn as a sort of placebo or sugar pill, thinking, “*I know porn does nothing for me, but if I think it does then on certain occasions it will be helpful.*" A sugar pill, although giving no actual physical help, can be a powerful psychological aid to relieve genuine symptoms and is therefore beneficial. Internet porn and habitual masturbation, however, aren't sugar pills. Why? Porn creates the symptoms it relieves and ceases to relieve them completely.

You may find it easier to understand the effect when related to a non-user or a successful user who has quit for several years. Take the case of a user who loses their partner. It's quite common at such times, with the best of intentions, to say, “*Have one harem visit, it’ll help calm you down.*" If the offer is accepted, it won't have a calming effect as there's no dopamine addiction and therefore no withdrawal pangs. At best, all it’ll do is give them a momentary psychological boost.

Even after the session is over, the original tragedy is there. In fact, it’ll be increased because the person now suffers withdrawal pangs and thus has to make a choice: endure them, or seek relief by repeating the water slide ride to start the chain of misery all over again. All the porn provided was a fleeting psychological boost, the same that could've been achieved by a book or feel-good movie, even a bad one. Many non-users and ex-users have become re-addicted as a result of such occasions. Get it quite clear in your mind: you don't need the dopamine rush and are only torturing yourself further by continuing to regard it as some sort of prop or boost. There's no need to be miserable.

Orgasms don't make good relations, most times they ruin them. Remember too that it's not entirely true that those who show public displays of affection enjoy every occasion; intimacy is best enjoyed in private where partners can respond without embarrassment. You don't have to be an orgasm-induced dopamine addict. If it happens as a natural result of a series of life events, that's fine, but enjoy the occasion and life without it.

After abandoning the concept of porn as pleasurable in itself, many users think “*If only there were clean internet porn.*" There *is* clean soft porn, and any who try it soon find out that it's a waste of time. Get it clear in your mind that the only reason you've been using porn is getting the dopamine flush. Once rid of the dopamine craving for porn you’ll have no need to visit your online harem.

Whether the pangs are due to actual dopamine-withdrawal symptoms or trigger/cue mechanisms, accept it. The physical pain is non-existent and with the right frame of mind it won't be a problem. Don't worry about withdrawal — the feeling itself isn't bad. It's the association with wanting and then feeling denied that's the problem. Instead of moping about it, acknowledge it: “*I know what this is, it’s the withdrawal pang from porn. That’s what users suffer their entire lives and keeps them addicts. Non-users don’t suffer these pangs, it's another of the many evils of this lying addiction. Isn't it marvellous that I’m purging this evil from my brain!"*

In other words, for the next three weeks you’ll have a slight trauma inside your body, but during those weeks and for the rest of your life something marvellous will be happening. You’ll be ridding yourself of an awful disease, with the bonuses far outweighing the slight, temporary trauma, and actually enjoying withdrawal pangs. They’ll become moments of pleasure, like an exciting game to starve the pornographic tapeworm living inside your stomach. You've got to starve it for three weeks while it's trying to trick you into getting into bed to keep it alive.

At times, it’ll try to make you miserable. At times, you’ll be caught off-guard. You’ll receive a porn URL or stumble upon something online and forget that you've stopped, giving a slight feeling of deprivation when remembered. Be prepared for these tricks in advance, and whatever the temptation, get it into your mind that it's only there because of the monster inside your body and every time you resist the temptation you've dealt another mortal blow in the battle.

Whatever you do, don't try to forget about porn. This is one of the things that causes PMOers using the willpower method hours of depression. They try and get through each day hoping that eventually they’ll just forget about it. It's like not being able to sleep — the more you worry about it, the harder it becomes. In any event, you won't be able to forget about it, for the first few days the ‘little monster’ will keep reminding you and you won't be able to avoid it. While there are still laptops, smartphones, and magazines around you’ll have constant reminders.

The point being that you have no need to forget, since nothing bad is happening. In fact, something marvellous and wonderful is happening and even if you’re thinking about it a thousand times a day, **savor each moment, remind yourself of how marvellous it is to be free again. Remind yourself of the sheer joy of not having to torture yourself anymore.** As said previously, you’ll find that pangs become moments of pleasure, being surprised how quickly you’ll then forget about porn.

Whatever you do, *don’t doubt your decision*. Once you start to doubt, you’ll start to mope, and it’ll get worse. Instead, use that moment of moping and convert it into a boost. If the cause is depression, then remind yourself that the porn was *causing* it. If you’re forwarded a URL by a friend, take pride in saying, “*I’m happy to say I don’t need that anymore.*" This will hurt them, but when they see it isn't bothering you they’ll be halfway to joining you.

**Remember: you have incredibly powerful reasons for stopping in the first place.** Remind yourself of the costs and ask yourself if you really want to risk the malfunction of your body, mind, and the simple fact you'll be living under a spell for the rest of your life. Be mindful of the little monster's efforts to minimise the hazards and above all, remember the feeling is only temporary, and every moment is a moment closer to your goal.

Some users fear they’ll have to spend the rest of their lives reversing ‘automatic triggers’. In other words, they believe they’ll have to go through their lives kidding themselves that they don't need porn, through use of psychology. This isn't so; remember that the optimist sees the bottle as half-full and the pessimist sees it as half-empty. In the case of pornography, the bottle is empty and the user sees it as full. There are no advantages to using internet porn. It's the user who's been brainwashed to think there are. Once you start telling yourself that you don't need or want porn, in a very short time you won't even need to say it, seeing the beautiful truth yourself. It's the last thing you need to do — make sure it isn't the last thing you do.
