# Just One Little Peek

This is the undoing of many using the willpower method. They'll go through three or four days and then have the odd peek to tide them over. They don't realise the devastating effect this has on their morale.

For most users, their first peek at the tube site harem was not as good as sex with a real person. The clips that are clean are few and far between, giving their conscious minds a boost, thinking, “*Good, that wasn't entirely all that enjoyable. I'm losing the urge and am not that into the shocking stuff.*" In fact, the reverse is the case. Get it clear in your mind, enjoyment of orgasm wasn't the reason you quit porn. If users were there for orgasm alone, they'd never watch more than one clip. The only reason why you needed porn was feeding that little monster. Just think, after being starved for four days how precious that one peek must have been to it. Your conscious mind is unaware, but the fix your body received is communicated to your subconscious, and all your sound preparation will be undermined. There'll be a little voice at the back of your mind saying that, in spite of all logic, the sessions are precious and you want another one.

That little peek has two damaging effects:

1.  It keeps the little monster alive in your body.

2.  Worse, it keeps the big monster alive in your mind. If you had the ‘last peek', it'll be easier to have the next one.

Porn is a mouse trap without cheese, only poison. Using willpower you have to convince yourself not to grab the cheese, but EasyPeasy allows you to see it's poison. You don't need to avoid it, you just don't go into it.

Above all, remember:

*‘Just one peek' is how people get into the addiction in the first place.*
