# Substitutes

Some examples of substitutes include restricting to porn magazines, static internet images, porn diets, etc. **DO NOT USE ANY OF THEM.** They make it harder, not easier. If you do get a pang and use a substitute it will just prolong the pang, making it harder. What you're really saying is that you need porn to fill the void. It'll be like giving in to a hijacker or a child's tantrum, just keeping the pangs coming and prolonging torture. In any event, the substitutes won't relieve the pangs. Your craving is for certain neurotransmitters in the brain, and all it'll do is keep you thinking about porn. Remember these points:

1.  There's no substitute for porn.

2.  You don't need porn. It's not food, it's poison. When the pangs come, remind yourself that it's users who suffer withdrawal pangs, not non-users. See them for what they are, another evil of the drug. See them as the death of a monster.

3.  Internet porn creates the void; it doesn't fill it. The quicker you teach your brain that you don't need to watch, the sooner you'll be free. In particular, avoid anything that resembles porn, such as men's magazines, movies, romance novels, and commercials. This isn't being closed-minded, it's okay to talk romance and sex, but not porn. There is always a way to find when and where to discriminate. It's true that a small proportion of users who attempt to quit using softcore porn or porn diets do succeed (from their own perspectives), and attribute their success to such use. However, they quit in *spite* of their use and not because of it. It's unfortunate that many still recommend these measures.

This is unsurprising because if you don't fully understand the porn trap, a diet or soft substitute sounds very logical. It's based on the belief that when you attempt to quit porn, you have two powerful enemies to defeat:

-   Breaking the habit.

-   Surviving terrible physical withdrawal pangs.

If you have two powerful enemies to defeat, it's sensible to not fight them simultaneously, but one at a time. So the theory goes that when you first stop using porn, you cut down to once a week or use safe porn. Then once the habit is broken, gradually reduce the supply, thus tackling each enemy separately.

This sounds logical, but is based on incorrect information. Porn isn't habit, but dopamine addiction, and the actual physical pain from withdrawal is almost imperceptible. What you're trying to achieve when quitting is killing both the monsters in your body and brain as quickly as possible. All substitution techniques do is prolong the little monster's life, and in turn this prolongs the brainwashing. EasyPeasy makes it easy to quit immediately, killing the brainwashing before your final session. The little monster will soon be dead, and even while it's dying, it'll be no more of a problem than it was when you were a user.

Just think, how can you possibly cure addiction to a drug through recommending the same drug? There are many stories online about those who've quit using hardcore internet porn, but are hooked on ‘safe' alternatives, having fallen for their little monster's justifications. Don't be fooled by the fact that the safe porn isn't awful — so was that first high-speed clip. All substitutes have exactly the same effects as any porn. Some even begin eating, but although the empty feeling of wanting a session is indistinguishable from hunger for food, one won't satisfy the other. In fact, if there's anything that's designed to make you want porn, it's stuffing yourself with food. As previously explained, porn diets and safe porn will only put you in the middle of the tug-of-war, with resistance to temptation being so annoying that you'll feel relieved visiting your favorite online harem.

The chief evil of substitutes is prolonging the real problem, brainwashing. Do you need a substitute for the flu when it's over? Of course you don't. By saying you need a substitute for porn, what you're really saying that you're making a sacrifice. The depression associated with the willpower method is caused by the fact that the user believes they're making a sacrifice. All you'll be doing is substituting one problem for another. There's no pleasure in stuffing yourself with food, cigarettes or alcohol. You'll just get fat, miserable and in no time at all you'll be back on the drug.

Casual users find it difficult to dismiss the belief they're being deprived of their little reward, like those who aren't allowed to go online during a period of time during travel, a family event, etc. Some say, “*I wouldn't know how to unwind if it weren't for porn.*" That proves the point — often the break is taken not because the user needs or even wants it, but because the addict — which is what they are — desperately needs to scratch the itch.

Remember, the porn sessions were never genuine rewards. They were equivalent to wearing tight shoes in order to feel the pleasure of taking them off. So if you feel that you must have a little reward, let that be your substitute; while you're working wear shoes or underwear a size too small, and don't allow yourself to remove them until you have your break, then experience the wonderful moment of relaxation and satisfaction when they're removed. Perhaps you feel that would be rather stupid. You're absolutely right. It can be difficult to visualise whilst still in the trap, but that's what users do. It's also hard to visualise that soon you won't need that little ‘reward' and that you'll soon regard friends who are still in the trap with genuine pity and wonder why they cannot see the point.

However, if you continue kidding yourself that the online harem visit was a genuine reward, or that you need a substitute, you'll feel deprived and miserable. The chances are that you'll end up falling into the disgusting trap again. If you need a genuine break as housewives, teachers, doctors, and other workers do, you'll soon be enjoying that break even more because you won't have to addict yourself. Remember that you don't need a substitute. The pangs are a craving for dopamine and will soon be gone. Let that be your prop for the next few days and enjoy ridding your body and mind of slavery and dependence.
