# Should I Avoid Temptation Situations

The advice has been direct so far and has asked you to treat it as instruction rather than suggestion. There are sound, practical reasons for this advice and those reasons have been backed up by thousands of case studies. On the question of whether or not to try and avoid temptation, this isn't the case. Each user will need to decide for themselves. However, two helpful suggestions can be made to assist you through this process. It's fear of future withdrawal pangs that keeps us using porn for the remainder of our lives and this fear consists of two distinct phases.

**Phase One - “*How can I survive without porn?*"**

This fear is the panicky feeling the user gets when they're single or have an asexual, uninterested or unavailable partner. The fear isn't caused by withdrawal pangs but is the psychological fear of dependency, of being unable to survive without sex and orgasm. It peaks when on the verge of quitting, when your withdrawal pangs are at their lowest. It's the fear of the unknown, the sort of fear that people have when they're learning to dive.

The diving board is one foot high but appears to be six feet high. The water is six feet deep but appears to be one foot deep. It takes courage to launch yourself, convinced you're going to smash your head. The launching is the hardest part, if you find the courage to do it — the rest is easy! This explains why many strong-willed users have never attempted to stop, or can survive for only a few days when they do. In fact, there are some users on porn diets who, upon deciding to stop, actually binge and escalate to harsher clips more quickly than if they hadn't decided to stop. The decision causes panic, which is stressful and triggers a cue to take a trip to the harem. But now you can't have one, leading to thoughts of deprivation, compounding stress.

The trigger activates quickly when the fuse blows and you fire up the browser. Don't worry, the panic is just psychological. It's the fear that you're dependent. The beautiful truth is that you aren't, even when still addicted. Don't panic and launch yourself.

**Phase Two - Longer Term Fear**

The second phase is long-term, involving fear that certain situations in the future won't be enjoyable or you won't be able to cope with trauma without porn. Don't worry, if you can launch yourself, you'll find the opposite to be the case. The avoidance of temptation itself falls into two categories.

1.  “*I'll subscribe to a porn diet of once in four days. I'll feel more confident knowing I can go online if it gets difficult. If I fail it's okay, I'll just add additional days to my next cycle.*"

    The failure rate with people doing this is **far higher** than those quitting altogether. This is mainly due to the fact that if you're having a bad moment during the withdrawal period, it's easy to hop on the browser and visit the harem with the above excuses. If you have the indignity of clearly breaking your own rules like a shattered glass window, you're more likely to overcome the temptation. In any event, the pang would probably already have passed if you'd delayed it. However, the main reason for the high failure rate in these cases is that the user didn't feel completely committed to stopping in the first place. Remember the two essentials to succeed are:

    -   Certainty.

    -   “*Isn't it marvellous that I don't need porn anymore?*"

    In either case, why on earth do you need a session? If you still need to visit your harem, re-read the book first. Something hasn't quite gelled. Take the time to kill the big brainwashing monster in your mind stone-dead.

2.  “*Should I avoid stressful or social occasions during the withdrawal period?*"

    In the case of stressful situations, yes. There's no sense putting undue pressure on yourself. In the case of social events, like bars or clubs, the advice is the reverse. Go out and enjoy yourself straight away! You don't need sex or the propagative side of sex even while you're addicted to porn. Go out and rejoice in the fact that you don't have to have sex or propagative sex, it'll quickly prove to you the beautiful truth that life is so much better without these pressures. Just think of how much better it will be when the little monster has left you, together with those needy thoughts.
