# The Moment of Revelation

Usually within three weeks post-escape, ex-users experience the moment of revelation. The sky appears to become brighter and it's the moment when the brainwashing ends completely. When instead of telling yourself you don't need to watch porn, you suddenly realise that the last thread is broken and you can enjoy the rest of your life without ever needing it again. It's also from this point that you usually start looking at users as objects of pity.

Quitters using the willpower method don't normally experience this moment because although they're glad to be ex-users, they continue moving through life believing they're making a sacrifice. The more you were addicted, the more marvellous this moment is, and it lasts a lifetime. While there are many joys in life, it's impossible to recapture the actual feeling of experiencing them. The joy of not having to watch porn anymore is different, if feeling low and needing a boost, remind yourself of how lovely it is not to be hooked on that awful addiction. Many list it as one of the greatest events of their lives. In most cases, the moment of revelation takes place not after three weeks, but after a few days.

In my own case, it happened before finishing my last harem visit. I'm sure many of the readers here, before they'd even got to the end of the chapters would say something like “*You needn't say another word. I can see it all so clearly, I'll know I'll never need porn again.*" Based on feedback received, this happens frequently. Ideally, if you follow all the instructions and understand the psychology completely, it should happen to you immediately.

While it's stated that it takes around five days for noticeable physical withdrawal to go, and about three weeks for an ex-user to get completely free, such guidelines can cause two problems. The first being that the suggestion is implanted in people's minds that they'll have to suffer for between five days and three weeks. The second is that the ex-user tends to think “*If I can survive for five days or three weeks, I can expect a real boost at the end of that period.*"

However, they may have five pleasant days or three pleasant weeks then followed by disastrous days that strike everyone, which have nothing to do with addiction but are caused by other factors in our lives. Then our ex-user who's waiting for the moment of revelation experiences depression instead. It could destroy their confidence. By the same token, if there were no guidelines, the ex-user could spend the rest of their life waiting for nothing to happen. This is what happens to the vast majority of those who stop using the willpower method.

People often ask about the significance of the five days and three weeks. Are they just periods drawn out of the blue? No, while they aren't definite dates they reflect an accumulation of feedback from over the years. About five days after stopping is when the ex-user ceases to have the addiction as the main occupation of their mind. Most ex-users experience revelation around this period, generally in stressful or social situations that at one point they weren't able to cope with or weren't enjoyable without a harem visit. You suddenly realise that not only are you enjoying or coping with it, but the thought of porn has never even occurred to you. From that point it's usually plain sailing. That's when you know you're free.

It's both mine and the experience of many others attempting to stop using the *willpower method* that around the three week period is when most serious attempts to stop fail. What usually happens is that after about three weeks you sense you've lost the desire to watch porn. You need to prove this to yourself, so you hop on the browser to visit your harem. It feels weird, proving you've kicked it. But in the process you're greased the DeltaFosB water slide thanks to the fresh dopamine rush, what your body has been craving for the last three weeks. As soon as you finish the deed, the dopamine starts to leave your body. A little voice reappears, “*You haven't kicked it, you want another one.*"

You don't scurry back right away because you don't want to get hooked again, allowing a safe period to pass. When you're next tempted you're able to say to yourself “*Well, I didn't get hooked again, so there's no harm in having another one."* You're already on your way down the slippery slope. The key to the problem isn't waiting for the moment of revelation, but to realise that once you close the browser it's finished. You've cut off the supply of oxygen to your little monster. No force on Earth can prevent you from being free, *unless you mope about it or wait for revelation.* Go and enjoy life; cope with it right from the start. The moment will soon arrive.
