# The Final Visit

Having decided on timing, you're now ready to visit your harem one last time. Before you do so, check on the two essentials.

1.  Do you feel certain of success?

2.  Do you have a feeling of doom and gloom, or a sense of excitement that you're about to achieve something marvellous?

If you have any doubts, re-read the book first. Remember that you never decided to fall into the porn trap, but the trap is designed to enslave you for life. In order to escape, you need to make the positive decision that you're about to stop and to make your final visit.

Remember, the only reason you've read this book so far is because you'd dearly love to escape. So make that positive decision now, making a solemn vow that when you close your private browser window, whether finding it easy or difficult, you'll never visit your harem again. Perhaps you're worried that you've made this vow several times in the past and are still failing, or that you'll have to go through awful trauma. Have no fear, the worst thing that can possibly happen is that you fail, so therefore you have ***absolutely nothing*** to lose and so much to gain.

But stop even thinking about failure — the beautiful truth is that it's not only ridiculously easy to quit, you can actually enjoy the process. This time you're going to use EasyPeasy! All you need to do is follow the simple instructions about to be given.

1.  Make the solemn vow now and mean it.

2.  Browse the pictures and clips on your favorite tube site consciously, looking at the desperate attempts by the site administrators, actors and even amateurs to amplify the shock, novelty and supernormal nature of their wares and ask yourself where the pleasure is.

3.  When you finally close the browser, don't do so with a feeling of “*I must never visit another online harem again*" or “*I'm not allowed to visit another*" but instead with a feeling of freedom, like “*Isn't it great? I'm free! I'm no longer a slave to porn! I don't ever have to visit these filthy sites in my life again.*"

4.  Be aware that for a few days, there'll be a little porn saboteur inside your stomach. You might only be aware of the feeling of wanting a session. The little porn monster has been referred to as the slight physical craving for dopamine. Strictly speaking this is incorrect, and it's important to understand why. Because it takes up to three weeks for that little monster to die, ex-users believe the little monster will continue to crave after the final online harem visit, and therefore they must use willpower to resist the temptation during this period. This isn't so, the body doesn't crave porn-triggered dopamine; only the brain craves.

If you do get that feeling of wanting a peek over the next few days, your brain has a simple choice. It can either interpret that feeling for what it actually is — an empty, insecure feeling started by the first visit to an online porn site and further perpetuated by each subsequent one, and saying to yourself **"YIPPEE! I'M A NON-USER!"**

Or, you can start craving for porn and suffer for the remainder of your life. Just think for a moment, wouldn't that be an incredibly stupid thing to do? To say, “*I never want to watch porn again*" and then spending the rest of your life saying “*I'd love a visit*"? That's what those using the willpower method do, and it's no wonder they feel so miserable. Spending the rest of their lives desperately moping for something they desperately hope they'll never have. No wonder that so few succeed and the few that do never feel completely free.

> *‘Get this mental picture clearly in your mind, for it can be quite helpful in overcoming the power of external stimuli to disturb you. See yourself sitting quietly, letting the phone ring, ignoring its signal, unmoved by its command. Although you are aware of it, you no longer mind or obey it. Also, get clearly in your mind the fact that the outside signal in itself has no power over you, no power to move you. In the past you have obeyed it, responded to it, purely out of habit. You can, if you wish, form a new habit of not responding.*
>
> *‘Also notice that your failure to respond does not consist in doing something, or making an effort, or resisting or fighting, but in doing nothing — in relaxation from doing. You merely relax, ignore the signal, and let its summons go unheeded. The telephone ringing is a symbolic analogy to any and every other outside stimulus you might habitually give control over to and now choose to very intentionally alter that habit.*'
>
> ---  Maxwell Maltz, *The New Psycho Cybernetics* Ch. 12. 

It's only doubting and waiting that makes it difficult to quit, ***so never doubt your decision*** because you know it's the correct one. If you begin to doubt it, you'll put yourself in a no-win situation. Miserable while craving a visit, but unable to have one. No matter what system you are using, what are you trying to achieve when quitting porn? Never to watch again? No! Many ex-users do that but go through the rest of their lives feeling deprived.

What's the difference between users and non-users? Non-users haven't any need, nor desire to watch porn, they're without craving and don't need to exercise willpower in order to not watch it. That's what you're trying to achieve and it's completely within your power to do so. You don't have to wait to stop craving porn or become a non-user, it's completed the moment you close that final browser window, cutting off the supply of dopamine. **YOU ARE ALREADY A HAPPY NON-USER!**

You'll remain a happy non-user provided:

1.  You never doubt your decision.

2.  You don't wait to become a non-user. If you do, you'll merely be waiting for nothing to happen and creating a phobia.

3.  You don't try *not* to think about porn or wait for the ‘moment of revelation' to come, creating a phobia.

4.  You don't use substitutes.

5.  You see all the other users as they really are and pity them rather than envying them.

Whether they're good or bad days, don't change your life just because you've quit. If you do, you'll be making a genuine sacrifice when there's no need to. Remember, you haven't given up living. You haven't given up anything. On the contrary, you've cured yourself from an awful disease and escaped from an insidious prison. As days pass and your health — both physically and mentally — improves, the highs will appear higher and the lows less low than when you were a user. Whenever you think about porn during the next few days or the rest of your life, think:

***“YIPPEE! I'M A NON-USER!"***

## A Final Warning

No user, if given the chance of going back to the time before they became hooked, with the knowledge they have now, would opt to start. Tens of thousands who successfully kick the habit for many years lead perfectly happy lives, only to get trapped once again. I trust this book will help you to find it relatively easy to stop. But be warned, users who find it easy to stop find it just as easy to start again. **Do not fall for this trap.**

No matter how long you've stopped for or how confident you are never going to become hooked again, make it a rule for life not to watch porn for any reason. Resist the allusions and innuendos in the media, and remember how they're pushing their image of ‘openness' by bringing porn into the mainstream, unaware that porn and compulsive masturbation are killers of relationships and of the personal sense of well-being for a huge number of men and increasing numbers of women.

Remember that that first peek or visit will do nothing for you. You'll have no withdrawal pangs to relieve and it will make you feel awful. What it will do is put the pleasure of the dopamine rush into your mind and brain, and a little voice at the back of your mind will be telling you that you want other one. Then you've got the choice of being miserable for a while, or starting the whole filthy chain again.
