# Feedback

The war isn't against users, but the porn-industry trap, and it's waged for the simple reason that I enjoy waging it. Every time I hear about a user escaping from the prison I get a feeling of immense pleasure. But this pleasure hasn't been without considerable frustration, mainly caused by two categories of porn user. In spite of the warning in the previous chapter, I'm continually surprised by the number of those who find it easy to stop, yet later get hooked and find they can't succeed the next time.

It's like finding someone up to their neck in a swamp and about to go under. You help pull them out and they're grateful but then, six months later dive straight back into the swamp. Users who find it easy to stop and start again pose a special problem, however when you get free ***PLEASE, PLEASE, DON'T MAKE THE SAME MISTAKE.*** They believe such people start again because they're still hooked and are missing the dopamine. In fact, they find stopping so easy that they lose their fear of porn. They think, “*I can have an odd session, and even if I do get hooked again, I'll find it easy to stop.*"

I'm afraid it just doesn't work that way, because it's easy to stop porn but impossible to control the addiction. The one thing essential to stopping porn is not using it.

People usually come back to porn because they misunderstand the “easy" in EasyPeasy.

Imagine someone sitting on the cold concrete floor of a freezing room. On the wall opposite to them there's a window showing a perfect spring day outside — trees gently swaying, birds chirping — right next to an unlocked door. 

Does it take any willpower getting out of that freezing room? No! Is escaping any harder than staying? Of course not! (In fact, it's a little easier because of the body moving). Why would anyone in their right mind put themselves in such a situation, causing themselves months or years of frustration unless they were tricked?

EasyPeasy pushes aside curtains so the user can see outside clearly and to remove **delusions** about how terrible outside can be and how comfortable the user is in the room.

The other category of frustrating users are those too frightened to make the attempt to stop, or when they do, find it a great struggle. The main difficulties appear to be the following.

**Fear of failure.**

:   There's no disgrace in failure, but not trying is plain stupidity. Look at it this way, you're hiding from nothing. The worst thing that can happen is that you fail, in which case you are no worse off than you are now. Just think how wonderful it would be to succeed. If you don't make the attempt, you've already guaranteed failure.

**Fear of pain and being miserable.**

:   Don't worry about it, just think: what awful thing could happen to you if you never watched porn again? Absolutely nothing. Terrible things *will* happen if you do; re-read the notes on Pascal's Wager. In any case, the panic is caused by dopamine and will soon be gone. The greatest gain is being rid of that fear. Do you really believe that users are prepared to have fading penetrations, unreliable sexual performance, or the illusory pleasure they get from porn? If you find yourself getting panicky, deep breathing will help. If you're with other people and they're getting you down, escape from them and go to the garage, an empty office or somewhere.

    If you feel like crying, don't be ashamed. Crying is nature's way of relieving tension. No one has ever had a good cry without feeling better afterwards. One of the awful things we do to young men is conditioning them not to cry. You can see them trying to fight back the tears, but watch the jaw grinding away. We teach ourselves not to show emotion, but we're not meant to bottle them up inside. Scream, shout or have a tantrum. Kick something. Regard your struggle as a boxing match that you cannot lose. Nobody can stop time, every moment that passes that little monster inside you is dying. Enjoy your inevitable victory.

**Not following the instructions.**

:   Incredibly, some users say that the method didn't work for them. They then describe how they ignored not only one instruction but practically all of them. For clarity, these are summarised as a checklist at the end of this chapter.

**Misunderstanding instructions.**

:   The chief problems appear to be these:

    “*I can't stop thinking about porn.*"

    :   Of course you can't and if you try, you'll create a phobia, becoming miserable. It's like trying to get to sleep at night: the more you try, the harder it becomes. It doesn't matter if you think about porn for ninety percent of your life, it's what you're thinking that's important. If you're thinking “*Oh, I love to look at porn*" or “*When will I be free?*" you'll be miserable. If you're instead thinking “*YIPPEE! I'm free!*" you'll be happy.

    “*When will the little porn monster die?*"

    :   The dopamine flush leaves your body very rapidly, but it's impossible to tell when your body will cease suffering from the slight physical sensation of dopamine withdrawal. That empty, insecure feeling is identical to normal hunger, depression or stress. All porn does is increase the level of it. This is why users who stop using the willpower method are never quite sure if they've kicked it, even after their body has ceased suffering dopamine withdrawal. If suffering normal hunger or stress, their brain is still telling them this is a valid reason to claim their entitled session. The point being that you don't have to wait for the craving to go, since it's so slight that we don't even know it's there, only knowing it as a feeling of wanting. When you leave the dentist do you wait for your jaw to stop aching? Of course you don't, you get on with life. Even though your jaw's still aching, you're elated.

        Don't wait for withdrawals to leave because you'll create doubt by constantly asking yourself “*How long will this take? Am I even free if I don't feel any different?*" Fear is the actual pang, therefore waiting for life to get better after quitting will create doubt. Withdrawal is imperceptible unless you fear it, and the exponential improvements to neurology are slow, so if you wait to feel different, it'll feel like nothing is happening, creating doubt.

    *"The ‘moment of revelation' hasn't arrived yet."*

    :   If you wait for it, you're just causing another phobia. I once stopped for three weeks on the willpower method. Chatting with an old friend, he asked me how I was getting on.
        “*I've survived three weeks*", I replied.
        He queried, “*What do you mean, you've survived three weeks?*"
        I clarified, “*I've gone three weeks without porn.*"
        He said, “*What are you going to do? Survive the rest of your life? What are you waiting for, you've done it. You're a non-user.*"

        I thought, “*He's absolutely right, what am I waiting for?*" Unfortunately, due to lack of understanding of the trap, I was soon back in, but the point was noted. You become a non-user when closing your browser. The important thing is to be a happy non-user from the start.

    “*I'm still craving porn.*"

    :   Then you're being very stupid. How can you claim you want to be a non-user and then say that you want porn? That's a contradiction. If you say that you want porn, you're saying you want to be a user. Non-users don't want to visit the disgusting tube sites. You already know what you want to be, so stop punishing yourself.

    “*I've opted out of life.*"

    :   Why? All you have to do is stop killing yourself and start energising instead. You don't have to stop living in the slightest. It's as simple as this, for the next couple of days you'll have a slight trauma in your life. Your body will suffer the almost imperceptible aggravation of withdrawal from demands and claims for a dopamine surge. Now, bear this in mind: you're no worse off than you were. This is what you've been suffering for the whole of your life, every time you've been asleep, in church, the supermarket or library. It didn't seem to bother you while you were a user and if you don't stop, you'll go on suffering this distress for the rest of your life.

        Porn and orgasms don't make occasions, they deprive you of them. Even while your body is still craving dopamine, meals and social occasions are marvellous. Life is marvellous — go to social functions, even if there are naked dancers there. Remember that you're not being deprived, they are. Every single one of them would love to be in your position, if only they knew. Enjoy being the prima donna and centre of attention. Stopping porn is a wonderful conversation point, taking a secret pleasure they cannot. Your friends and peers will be surprised to see that you, formerly shying and tired-looking, are now happy and cheerful. You'll be enjoying life right from the start; there's no need to envy pick-up artists at parties, they'll be envying you — if only they knew.

    “*I'm miserable and irritable.*"

    :   This is a failure to follow instructions. Find out which one it is. Some people understand and believe everything written, but still start off with a feeling of doom and gloom, as if something terrible were happening. You're not only doing what you'd like to do, but what every user on the planet would like as well. With any method of stopping, the ex-user is trying to achieve a certain frame of mind, so every porn-related thought is punctuated by “*YIPPEE! I'M FREE!*" If that's your objective, why wait? Start off in that frame of mind and never lose it. There's no alternative.

    “*I had a good week / month / six months but I'm back in the trap.*"

    :   Remember, fear is the pang itself. Giving into a pang generates more fear, feeding the weakened little monster and succeeding in spooking the non-user into thinking they're hooked for life. In reality, their conceptualisation of the brainwashing hasn't changed, but they've given dopamine to the thought process. This is by definition falling forward but is a failure to follow instructions. Understand which one below and rejoice.

## The Checklist

If you follow these instructions, you cannot fail:

1.  Make a solemn vow that you'll never, ever, go online to visit your harem *OR* settle for static pictures *OR* make peace with erotic graphics *OR* anything that contains supernormal stimuli, and stick to your vow.

2.  Get this clear in your mind: There's absolutely nothing to give up. By that, it isn't meant that you will be better off as a non-PMOer (you've known this all along); nor that although there is no rational reason why you PMO, you get some pleasure or crutch from it, since otherwise you wouldn't do it. What's meant is there's ***no genuine pleasure or crutch in PMOing.*** It's just an illusion, like banging your head against a wall to get pleasure when you stop.

3.  There's no such thing as a confirmed PMOer. You're just one of the hundreds of millions who've fallen for the subtle trap. Like the millions of other ex-PMOers who once thought they couldn't escape, you've escaped.

4.  If at any time in your life you were to weigh up the pros and cons of PMOing, the overwhelming conclusion would always be “*Stop doing it. You're a fool!*" Nothing will ever change that. It's always been that way and always will be. Having made what you know to be the correct decision, don't ever torture yourself by doubting. Pascal's Wager perfectly applies to PMO, with no chance of loss, high chances of gains, and high chances of avoiding losses.

5.  Don't try not to think about porn, or worry that you're thinking about it constantly. Whenever you do think about it, whether today, tomorrow, or the rest of your life, think **“YIPPEE! I'M A NON-PMOer!"**

6.  **Do not** use any form of substitute. **Do not** challenge yourself by keeping your laptop next to you while you sleep. **Do not** avoid plays, movies or magazines. **Do not** change your lifestyle in any way purely because you've stopped. If you follow the above instructions, you'll soon experience the ‘moment of revelation', but:

7.  Don't wait for the ‘moment of revelation' to come. Just get on with your life, enjoying the highs and coping with the lows. You'll find in no time at all the moment will arrive.
