# Help Those on the Sinking Ship

Porn users are panicking nowadays, sensing changes in the way internet porn is perceived by men and women. Internet porn's addictive nature is being studied increasingly often, now rightly regarded as being different from traditional pornography. Effortlessness and availability raises alarm even in the hearts of porn supporters. They also sense that their crusade for free speech and thought is being hijacked by various elements. The wild west of the unpoliced internet makes it near-impossible to enforce age restrictions to supernormal stimuli. It's unfortunate that this won't come to an end anytime soon, but hundreds of thousands of users are stopping, with most addicts aware of studies showing similarities between porn and substance addiction. Each time a user leaves the sinking ship, the ones left on it feel ever more miserable.

Every user instinctively knows that it's ridiculous to self-sabotage and spend time in front of two-dimensional pixels, super-surging their brain and in the process developing neural pathways that guarantee poor sexual performance. If you still don't think it's silly, try talking to a porn magazine standing at the centre of your city and ask yourself what the difference is. Just one. You can't get the pleasure of warmth and intimacy that way. If you can stop buying alcohol and cigarettes every time you go grocery shopping, you can definitely stop visiting your online harem. Users can't find rational reasons for watching porn, but they don't feel quite so silly if other people do it too.

Users blatantly lie about their habit, not just to researchers and those around them, but to themselves. They have to — the brainwashing is essential if they're to retain some self-respect. They feel the need to justify their ‘habit' not only to *themselves* but to non-users. They're forever advertising the illusory advantages of porn by subtler means.

If a user stops by using the willpower method they still feel deprived, tending to become a moaner. All this does is to confirm to other users how right they are to continue using. If the ex-user succeeds in kicking the habit, they're then grateful they no longer have to go through life self-sabotaging or wasting energy and have no need to justify themselves. Remember, it's fear that keeps the user's head in the sand, only questioning their behaviour when stopping. Help the user by removing those fears. Tell them how marvellous it is not having to go through life living in a prison, how lovely it is to wake up in the morning feeling fit and healthy instead of lacking in energy and self-loathing, how wonderful it is to be free of slavery, to be able to enjoy the whole of your life and to be rid of those black shadows. Or better still, get them to read this book.

It's essential not to belittle a married user by indicating that they're deliberately ruining their relationship or it's in some way cheating or unclean. There's a common misconception that the ex-user is worst in this aspect. This conception has some substance, but is generally due to the willpower method of stopping. Because the ex-user — although having kicked the habit — still retains part of the brainwashing and still believes they've made a sacrifice. They feel vulnerable and their natural defense mechanism is to attack the porn user.

This might boost the ex-user's ego, but it does nothing to help the user. All it does is put their back up against the wall, making them feel even more wretched and consequently their need for porn even greater. Although the change in the medical establishment's attitude to internet porn is the main reason why many users are quitting, it doesn't make it any easier to do so. In fact, it makes it a great deal harder. Most users nowadays believe they're stopping primarily for health reasons. This isn't strictly true.

Although the enormous health risk is obviously the chief reason for quitting, users have been sabotaging their virility for years and it hasn't made the slightest bit of difference. The main reason why users are stopping is because society is beginning to see porn unmasked for what it is: drug addiction. Societies' attitudes are slowly changing: many partners would now ask questions if you're on your laptop in the middle of the night.

Complete bans on porn in some countries or the unavailability of internet are classic examples of the travelling user's dilemma. Generally they take the attitude that it will help them cut down on their intake. The result being that instead of one or two a day, neither of which they would have enjoyed, they abstain for an entire week. During this enforced period of abstinence however, not only will they be mentally deprived waiting for their reward, their body is craving too. Oh, how precious that online harem visit is when they're eventually allowed.

Enforced abstinences don't actually cut down the intake because the user just indulges themselves even more when finally allowed to be alone. All it does is to engrain in the user's mind how precious internet porn is and how dependent they are upon it. The most insidious aspect of this enforced abstinence is its effect on adolescents. We allow the hijackers of ‘freedom of expression', the porn producers, to target unfortunate teenagers to get them hooked in the first place. Then, at what is probably the most stressful period in their lives, when, in their deluded minds, they need porn most of all, we blackmail them into giving up because of the harm they're causing to themselves.

Many are unable to do so and are forced, through no fault of their own, to suffer a guilt complex for the rest of their lives. Many succeed and are pleased to do so, thinking, *\“Fine. I'll do this for now and after it's over I'll be cured anyway.\"* Then comes the pain and fear of finding work and other adult struggles, followed by the biggest ‘high' of their lives — finding a job. The pain and fear are over, now feeling secure, the old trigger mechanism comes back into operation. Part of the brainwashing still being there and before the smell of the new work laptop is gone, the user is at the threshold of their favorite online harem. The elation of the occasion blocks the foul feelings from their mind, they have no intention of becoming hooked again, but just one peek couldn't hurt\... Too late! They're already hooked again.

The old craving from the little monster will begin again and even if they don't become hooked again straight away, post-high depression will probably catch them out. It's strange that although heroin addicts are criminals in law, society's response is helping these individuals. Let's adopt the same attitude to the poor porn user. They're not doing it because they want to, but because they think they have to. Unlike the heroin addict, they usually suffer years upon years of mental and physical torture. We always say a quick death is better than a slow one, so don't envy the poor porn user. ***They deserve your pity.***
