# Advice to Non-users

## Help get your porn using friends to read this book

First, study the contents of this book and try to put yourself in the place of the user. Don't force them to read this book by telling them they're ruining their health or playing with fire. They know this better than you do. Users don't continue viewing porn because they enjoy it or because they want to, they only tell themselves and other people this in order to retain self-respect. They do it because they're dependent on porn because they think it relaxes them, gives them courage or confidence (pleasure or crutch) and because they feel that life will never be enjoyable without ‘sex' — at least their version of it. If you try and force a user to stop, they'll feel like a trapped animal and want their harem even more. This may turn them into a secret user and porn will become even more precious in their mind.

Instead, concentrate on the other side of the coin. Get them into the company of ex-users (blogs, forums, YBOP, NoFap, etc., though beware of advocacy for the willpower method). Get them to tell the user how they too thought they were hooked for life and how much better life is as a non-user. Once you have got them into believing they can stop, their mind will start to open up. Then start explaining the delusion created by withdrawal pangs. Not only are the ‘dopamine rushes' not giving them a boost, they're destroying their confidence and making themselves irritable and tired.

They should now be ready to read this book themselves, expecting to read pages upon pages of stories about unreliable arousal, fading penetrations, PIED, PE, etc. Explain that this approach is completely different and references to illness are tiny fractions of material.

In short, don't let this die in darkness. Tell your friends, but don't be weird about it. If you try to ‘win' the conversation or have a debate, you'll only succeed in alienating them and further increasing their fear.

## Should I tell my significant other?

Should I tell my wife, girlfriend or partner about my habit? (The intention being to assist you in quitting.) There's multiple factors at play here.

If you've already been failing to quit using the willpower method and have already told your partner, tell them about your new approach and allow them to educate themselves by reading the book. They'll be able to assist and motivate you during the withdrawal period and are a stronghold when the little monster attempts to trip you up.

If you've only just become aware of the existence of the porn trap and haven't attempting quitting in the past, first use EasyPeasy yourself. As explained previously, this should be a enjoyable experience. However, if you're finding it difficult, request their assistance. Be open and vulnerable with your partner and it'll strengthen your relationship.

Provided you're enjoying escaping and aren't finding it difficult through indecision, there isn't much reason to let your partner know. If it wasn't an issue in the past, let it die. However, be prepared that your partner might wonder why you're looking, feeling and performing better!

## My partner is quitting porn

Pornography is a perverse destroyer of relationships and while quitting can be done instantly, healing takes time. Many users, due to irrational beliefs spawned from their addiction, take out their anger on partners and loved ones. These behaviours manifest in gaslighting, lying and manipulative behaviours. This isn't all users, but it's increasingly common in later stages of the disease. While these behaviours may have manifested from the underlying porn addiction, it's important to educate yourself about these behaviours and if recognised, consider seeing a therapist specialising in sexual addictions.

If your partner is within the withdrawal period, assume they're suffering whether they are or not. Don't attempt to minimise it by telling them it's easy to stop, they can do that themselves. Instead, continue telling them how proud you are, how much better they're looking, how much sweeter it is to be with them and how much easier they are in general. It's particularly important to keep doing this, because when a user makes an attempt to stop, the euphoria of the attempt and the praise they get from peers can help them along. However, they tend to forget quickly, so keep the praise coming.

Because they're not talking about porn, you may think they've forgotten and don't want you to remind them. Usually the complete opposite is the case with the willpower method, as the ex-user tends be obsessed with nothing else. So don't be frightened to bring the subject up and keep praising them (they'll tell you if they don't want to be reminded).

Go out of your way to relieve them of pressures during the withdrawal period, thinking of ways to make their life interesting and enjoyable. This can also be a trying period for non-users who've never had the addiction. If one member of a group is irritable, it can cause general misery all-round. So anticipate this if the ex-user is feeling irritable, they may well take it out on you, but don't retaliate, it's at this time they need your praise and sympathy the most. If you're feeling irritable yourself, which is understandable, try not to show it.

One of the tricks an addict will play when trying to give up with the aid of the willpower method is getting in tantrums, hoping that their partner or friends would say “*I can't bear to see you suffering like this. For goodness sake, just take your poison.*" The user therefore doesn't have to lose face, since they aren't ‘giving up', they've been instructed. If the ex-user pulls this ploy, on no account encourage them to relapse. Instead say, “*If this is what porn does to you, thank goodness you'll soon be free. How marvellous that you had the courage to give it up.*"

Remember, there are two healing parties within the recovery journey. When your partner is quitting porn, it's important to have your own support network, self-care routines and boundaries. This process doesn't happen overnight, requiring trust, communication and accountability. Journaling, developing your own passions and most importantly, therapy, assist this process.

## Slipping (relapse)

The existence of this section should serve as warning to those leaving the trap. Personally, I have never relapsed, but I will use experiences from interviews with community members and tools from cognitive behavioural therapy to illustrate.

Firstly, calling it a relapse is counterproductive. All that's happened is that you've slipped and fed the little monster, which in turn starts up the big brainwashing monster. Users who slip (which, is by definition falling forward) typically spawn a whole range of irrational beliefs:

  - “*I'll never be free*" - **Catastrophising**
  - “*I should / must exercise, study and be fruitful every single day of my life*" (aka - **Musterbating**)
  - “*Today I PMOed, so what's even the use of reading all the books and forums... My goal was to not even do M, but here I am — a failure — relapsing.*" - **Low Frustration Tolerance**
  - “*My friends / forum readers / others are doing no PMO for (n) days, but I can't so I'm a hopeless case. Felt good yesterday since I studied well and was fruitful, but today I didn't... I'm going downhill.*" - **Rating Between Self and Others**
  - "I shouldn't have sexual thoughts" - Themselves, parents or their society as a whole has installed **rigid beliefs** in relation to sex. Ask yourself if self-flagellation is helping you reach your goals, and if you are, are you enjoying the journey?

Factors that culminate to each user's brainwashing are seemingly infinite. You know yourself better than anyone else, but it's obviously a failure to follow instructions. You saw value in pornography, but how?

What's often overlooked is that it takes time to reverse the brainwashing. This doesn't make it any harder, but nearly every industry uses sex, and actively countering brainwashing is a conscious process (at least to begin with), so it might take time to fully solidify the lessons contained within. Hence, multiple readings are recommended (you can skip to chapters you're having difficulty with) and shouldn't take you long.

A surprisingly common experience for religious users leaving the trap is wanting it to hurt a little bit, as a form of atonement. They find quitting so easy, then feel guilty for feeling this way. But why self-sabotage and make it hard? The little monster is very sneaky in this regard.

Disassociate yourself from the little monster — it was added by the porn industry long ago. Imagine a bully having a tantrum on the school playground. What do you say to a bully? If you give in, you'll just reinforce them. Some who quit end up feeding the bully, and so increase their brainwashing, but their conceptualisation of the trap hasn't changed. Pick yourself up, figure out where you went wrong, and enjoy freedom!

You're not your urge. Mindfulness meditation is the practice of noticing thought, and there are fundamental lessons in the nature of the mind to be found. It's highly recommended that you meditate in general, and it's also completely compatible with religious practice. You can't fight with yourself, or with the little monster. You've got to unconditionally love yourself and the process.

But remove failure from your mind. Here's a section from “*Meditations of a Porn Addict*" by Gulliaco (linked in the Resources section at the end of the book):

> Since watching porn offers you zero benefits, it's something that only hurts you, and it's extremely ridiculous to want to do something like that, I compare it to drinking bleach. Here you go:
>
> **The hard journey of not drinking bleach.**
>
> Hi! We are NoBleach and we host rebooting challenges in which participants ("Bleachstronauts") abstain from drinking bleach for a period of time. Whether your goal is casual participation in a monthly challenge as a test of self-control, or whether excessive bleach drinking has become a problem in your life and you want to quit for a longer period of time, you will find a supportive community and plenty of resources here.
>
> - “*Sometimes I allow myself to drink one or another glass of bleach. I know about that the “one drop” is a lie, but I don’t think a single glass will hurt. One cannot destroy all the hours that I have spent without doing so.*”
> - “*I don't have a problem stopping drinking bleach, but sometimes I go down the street, and I see someone drinking water, you know, in a glass, and I imagine that the glass has bleach in it. Then I have a craving and, after debating with myself whether I should do it or not, I finally give in at night and drink a glass.*”
> - “*Look, my problem is that sometimes, when I'm alone in my kitchen, I start to see the glasses, sometimes I tempt myself by opening the container where I keep the bleach, sometimes I smell it and… Well, I end up right back where I started. I'm so desperate to stop this, but I'm not sure if I'll ever be
able to stop.*”
> - “*Stopping drinking bleach is impossible, I mean, I always have a mouth, you know? How am I supposed to stop if I always have a throat which reminds me that I can swallow bleach?*”
> - “*Oh man, it was going so well, 19 whole days without doing it. The important thing is to learn from failure! Now I know what to avoid doing: looking at cleaning products in the supermarket. I will try to make it to a month! I'll reset my counter. Wish me luck!*”

> If you have an urge, calm down dude! Remember what the hackbook says:
>
> “*Bleach is difficult to give up because of fear we’re being deprived of our pleasure or prop. The fear that certain pleasant situations will never be quite the same again. The fear of being unable to cope with stressful situations. In other words, it’s the effects of brainwashing deluding us into believing that buying bleach, and by extension drinking it, is a must for all human beings. Even further, it’s the belief there’s something inherent in affordable bleach that we need, and that when we stop using we will be denying ourselves and creating a void. Make this clear in your mind: Bleach doesn’t fill a void, it creates one!*”
> 
> And I say:
> “*Suppose you're forced to watch a glass full of bleach for five minutes. Try to remember one of those brands or smells that you liked so much. Maybe it's accompanied by some sound, or you only remember selected details. The bleach is there and you can't close your eyes or turn your head, because this bleach is in your mind, it's a memory recorded in you.*
>
> *Do you feel any craving? Do you feel anything in your tongue or any change in your breathing? What are your feelings about what you are remembering? Get them identified, the bleach wants to cloud them, make them confusing and make you only pay attention to that which wants to catch you.*”
>
> With the above, I am not trying to dismiss your feelings, much less say something like "haha me smart you dumb", but to give you perspective so that you realize how ridiculously easy it is (and always will be) to overcome this addiction.
> Watching porn is not like an on/off switch where you say “*oh well, I'm in situation X, then I'll watch porn*". Fantasies! Lies! How often do you allow yourself to drink a glass of bleach? Never? Why? Because it's a horrible thing, that's why! How are you supposed to escape your addiction if you don't
realize that PMO is a horrible thing to do to yourself?

## What about MO (masturbation, orgasm)?

People have been wanking for eons without issue. To be clear, porn is the problem.

That being said, you can still get hooked on MO for the same reasons as porn, such as the ‘need-to-have-an-orgasm' mentality, mental escalation, forcing the body to have sex, and just plain hedonistic pleasure-seeking.

It's exceedingly likely that porn and masturbation have become deeply intertwined in your mind. Many users find they end up relapsing as a result of masturbating to porn-induced fantasies. As your brain rewires, you'll find this brainwashing eventually fades, but it's best to take a break from MO for a while. You should also seek out real sex in order to speed this process along.

This isn't an instruction, but evaluate it: reported benefits from semen retention are numerous — increased focus and energy, removal of ‘brain fog' and increased confidence, along with a slew of other benefits. From personal experience, there's a clear difference, and it's all down to how you sublimate this increased energy.

Speculating, and without strict scientific knowledge, the benefits might come down to couple of different factors.

- After orgasm, the brain releases prolactin, which inhibits dopamine release.

- Depriving your brain of dopamine flushes allows more uptake from simply living life.

- Semen is reabsorbed by the bloodstream after ~78 days, and is one of the best nutrients your body can get.

- Sublimating sexual energy into productive habits brings with it an extra layer of productivity.

You may wish to have sex without orgasm as well, which as mentioned earlier, is a wonderful sexual experience (often referred to as Karezza). You can strengthen your ability to do this by practicing Kegel exercises. From personal experience, the easiest and most effective way to target this muscle is stopping and starting your urine mid-stream (though be careful not to overdo it, which can cause problems of its own). Separation of the tantric and propagative parts of sex is one of the many bonuses of escaping the PMO trap (and my partners have loved it too!).

## Deviations from standard advice

This section is new, and is written somewhat apprehensively; even still, it must be mentioned.

Some people using EasyPeasy find their desire to watch porn becomes so reduced that they can't bring themselves to have a final session. **This is fine**, but don't underestimate the power of having one. Mindfully browsing and solidifying just how much you dislike PMO can be really powerful. Personally, I found it really useful and was happy to wash my hands clean of it, genuinely relieved to never have to do it ever again. However, your mileage may vary.

If you've already been free from the trap for a while and have just removed the brainwashing, there's no need to feed the little monster as it would just nag you. Enjoy freedom instead!

## Help end this scandal

Internet porn is one of the dangers in a free society, piggy-backing on the good-willed efforts of advocates for personal freedom. Surely the very basis of civilisation — the reason why the human species has advanced so far — is because we're capable of communicating our knowledge and experiences, not only to each other but to future generations. Even animals find it necessary to guard their offspring from life's pitfalls.

Porn producers aren't doing this in good faith, genuinely believing they help mankind, especially now as addiction to internet porn is widely studied. Perhaps in its initial stages people genuinely believed that porn educated people on intimacy, but authorities know that's a fallacy. No tube site makes genuine claims about education. The only claims made are about the shock, novelty and escalating qualities of their wares.

The sheer hypocrisy is incredible: as a society we otherwise get uptight about school bullying and objectification of the human body. Compared with internet porn, these problems are mere pimples. Numbers of those addicted climb to new heights each year, spending quality time with imaginary and illusory pixel people at the expense of their health, virility, energy and time. It's by far the biggest killer in relationships, and hundreds of thousands of lives are ruined every year because they get hooked. Internet porn producers don't advertise in mainstream publications — they don't need to, our biological urges lead us to the thresholds of their well stocked harems, giving out free samples like the local drug dealer. Nowadays, the tube sites don't so much stock the wares as much as they encourage visitors to post content.

How clever that porn companies show *18+* warnings as the deterrent for underage users, though some don't even bother to do that. Internet porn affects everyone at all ages. “*We warned you of the danger, so it's your choice*," is their attitude. Do they take any steps to verify age? No, that would discourage their customers. Of course, if age verification is legislated, they'll just find another country to operate from. Or, will they pay some ‘elite' to write about how prohibition resulted in bootlegging and the creation of the Mafia? Conveniently forgotten is the question of why repealing prohibition didn't result in the reduction of alcohol-related casualties, and the failure of law enforcement to control the Mafia's growth.

We can address this differently by educating the younger generation. If they can step around cigarettes and alcohol when shopping, they can do the same with internet porn. We're already seeing societal shifts such as ‘No Nut November' and ‘Coomer' memes becoming mainstream. The user doesn't have the choice any more than the heroin addict does. Users don't decide to become hooked, they're lured into a subtle trap. If they had the choice, the only users tomorrow morning would be adolescents just starting out, believing they could stop at any time if they wanted to.

Why the phony standards? Why are heroin addicts seen as criminals, yet can register as addicts and get methadone and proper medical treatment to assist in getting off it? Just try registering as a porn addict — if you go to your doctor for help, they'll either tell you: “*Stop doing it so much, try moderation*," which you already know won't work, or will prescribe medication to address your ‘depression'. Worse is the advice to go and find real partners — seriously? Have they never heard of users who find porn better and do it behind their partner's back? Some people just don't understand.

Scare campaigns don't help users to stop, they make it harder. All they do is frighten users, which makes them want to watch even more. They also do not prevent teenagers from becoming hooked. Teenagers know that porn kills their libido, but they also know that one peek won't do it. Because the addiction is so prevalent, sooner or later the teenager — either through social pressures or curiosity — will try just one visit. Because free porn has awful clips, it's likely they'll become hooked.

Why do we allow this scandal to go on? Why don't governments come out with proper campaigns? Why aren't we told that that internet porn is a drug and killer poison, that it doesn't relax you or give you confidence, but destroys your nerves, taking just one peek to become hooked? Why can't they enforce age verification by requesting registered credit cards, perhaps with a third party? MindGeek, owner of many of the major porn sites, is attempting swindle governments into using their own proprietary age verification solution — don't let them do it! H. G. Well's *The Time Machine* describes an incident in the distant future where a man falls into a river. His companions merely sit around the bank like cattle oblivious to the cries of desperation. Inhuman and disturbing, much like society's general apathy to the porn crisis.

There is a wind of change of society. A snowball has begun rolling down the hill and it's hoped this book will help turn it into an avalanche. You too can help by spreading the message.

As such, to ask — if you see anyone struggling using willpower, or attempting to quit porn, kindly point them towards this method. However, the real task at hand is changing the narrative around porn in general. Please consider making a habit that if you see online or even experience porn's normalisation first-hand, you aim to *respectfully* educate and free them.

Occasionally, you might get a negative reaction, but sometimes a comment is all that's needed. As many have done before you, you can expect to receive messages from grateful people thanking you for their freedom.

## Final Warning

You can now enjoy the rest of your life as a happy non-user. In order to make sure that you do, you need to follow these simple instructions.

1.  Keep the following page in your bookmarks and refer to it as much as you need.

2.  If you ever start to envy another user, realise they'll be envious of you. You aren't being deprived. They are.

3.  Remember that you didn't enjoy being a user. That's why you stopped. You enjoy being a non-user.

4.  Remember, there's no such thing as just one peek.

5.  Never doubt your decision never to watch porn again. You know it's the correct one.

6.  If you have any difficulties, find and contact a therapist knowledgeable in internet porn. You can find lists of these online.
