# The End of The Book

Thank you for reading; as you know, it fills me with a sincere joy that you've found freedom.

I dream of a world where you didn't have to.

A world where you began questioning pornography before finding it, noticing the effects you'd learnt in school.

Where someone mentioning their favourite pornstar was met with that 'awkward social mistep' vibe, but immediately followed by a sincere desire to help.

One where everyone was a little less on edge; working together with local communities that are more sustainable, closer and considerate.

We're not as far off as you think.

## Where are we now? {-}

You exist where pornography has normalised into culture, media and everyday life. Rest assured this will not stand: the science is absolute, and all that stands with time must be based on truth.

You're witnessing a social shift against it; online communities, celebrated abstience months and conversations push the snowball -- but how long do you wish to wait?

## How so? {-}

Our goals are simple:

1. By the end of 2023, pornography education should be mandatory in all sexual education programs. There's simply no time to lose.
2. By the end of 2024, pornography is opt-in and age-restricted at the service provider level so that young children may avoid it.
3. By the end of 2025, Allen Carr's EasyWay should be at the forefront of nicotine campaigns.

## How can I help? {-}

Right now I'm crafting online communities to coordinate themselves.

You can use the following platforms.

**[Urbit](https://urbit.org/overview) ~mogsub-possum/coomer** -- you can find guides on [joining the network] and [using it] here.

**[Discord](https://discord.com/invite/bCXEnf9)** -- which is currently just shitposting central that I don't bother checking, but I'm working in the background with people to turn it into something cool.

**[Email](https://docs.google.com/forms/d/e/1FAIpQLSfi27XGmChe_qtu4fP6E6lNyjY8Ia_93TlfGbjbKgiI1VNdkg/viewform)** -- where you can sign up to get very occasional emails from me

So if you're anyone, from anywhere, with any skillset or amount of time spare, you'll be able to help freeing others.

It's not ready yet because it all has to be perfectly structured, but you can join the various channels now and chat.

### What about you? {-}

My name's Fraser, and I'm a 23 year old psychology student from Australia.

I'm really enjoying helping people, and I reckon the more people free from porn the better!

I'd prefer meeting you in person, but here's where I exist online.

**yt:** [Fraser Patterson](https://www.youtube.com/channel/UChMZhvS7eV-WoLDu_mRjEEw) -- Posting calm videos about my life, and little wisdom nuggets

**ig:** [@deleteinstaplease](https://instagram.com/deleteinstaplease) -- Occasionally, pictures of nature, or what I'm doing.

**tw:** [@deletetwitpls](https://twitter.com/deletetwitpls) -- I don't post here.

*Please don't feel pressured into following me*, but y'know, little bit of pressure because it gives me more 'clout' so that I can say to podcasts and stuff "hey mate mind if I pop on?"


## Wisdom Nuggets {-}

Quitting porn is the easy part, the 'hard' part is the journey ahead.

Here's some things that might help you on it.

If feeling you're **tech addicted,** understand that your thoughts match life's speed. Slow down your life through experiencing nature, and dry fasting for 24h in a dark room.

This isn't a 'cure all', but gives you time to think and peace with your thoughts.

Speaking of which, **mindfulness meditation** was recommended before.

Meditating is the practice of understanding how your mind always is. Thoughts continually arise, and pass away.

You'll be thinking about porn -- of course -- and meditating helps recognising them as just that: thoughts.

I'd highly recommend getting a [free month of Waking Up](
I'm not getting paid for recommending this, it's just a really, really great app. Would highly recommend the introductory course first, then some Alan Watts and Wisdom Texts by Jayasara. All very beautiful experiences.

Of course, **breathwork** would help even still.

I'd recommend Bukeuko and Wim Hof breathing techniques.

For now, put one hand on your belly, and one on your chest.

Then, breathe in whilst sticking out your lips in an O shape (yes.. haha xd!!)

You'll feel your diaphagm activate, which how you were naturally breathing as a baby. It's better for you in every way, and requires less effort from your body.

You picked up shallow breathing because everyone else is doing it, and we naturally mirror people.

Sound familiar?

Well, on addictions there's no doubt you'd enjoy quitting...

**Alcohol!**

Alongside creating a 10 day withdrawal, alcohol succeeds in 'stupifing' drinkers and doesn't give you enjoyment, confidence, courage or relaxation.

Jason Vale's book *Kick the Drink... Easily!" deconstructs alcohol fully and completely. He argues that there's no such thing as an alcoholic -- people who 'lose control' (of an addictive void) are just stigmatised and shunned -- and that quitting is extremely easy.

I quit alcohol after PMO, and I've found life and social occassions genuinely much more enjoyable without it.

A drug for numbing and poisoning yourself is very 'boomer', don't you think?

But perhaps everyone is simply victims of...

**Consumption.**

So, here's a quote about it.

>
>
...

>*I don’t often enjoy nor find much use in excessive deconstruction, but the act of contemporary entertainment begs such a process to drag it to court. Because that’s what most people forget when they’re watching TV or scrolling through their phone, it is an act, they are performing an action, however banal and mind-numbing it may be. Any action performed consistently eventually becomes a habit, at least in a certain sense, whether you like it or not. And at its root the action you are performing when one is engrossed within contemporary entertainment is apathy. That’s right, man has found a way to not only be actively apathetic, but also has found a way to cultivate this behaviour in such a way that it has become a virtue – “Bro, I spent all weekend watching Netflix!” Let’s take this apart, let’s have a look at how man decides to spend the life he has been given-*
>
>*There is a man or woman, plonked on a sofa. Their body in a strange unnatural position, all folded up and round, no point taking any more weight than any other, they’re a big pile of goo. They will remain here, just sat, in the same 4ft by 4ft space for hours end – the world is way bigger than this by the way – they’ll move their arm, maybe reposition, but that’s about it for using their body. As for their mind, it is quite literally working at its lowest setting. Unlike reading, learning, meditating, practicing or concentrating, contemporary acts of entertainment require nothing from the viewer, apart from one thing, that they stare in a certain direction. They are mediums of apathy. One could, if they so wished, be numbed all over, except for their eyes, and they would still be undertaking the act of being ‘entertained’, that is how pathetic this act is. I have nothing against what is on the TV, nor anything against visual media, what I am against is media which is a means to an end. People no longer like TV shows or specific films, they like Netflix, or watching-TV as a whole. They’re favorite pastimes are being apathetic to all that they can be. It is once again a question of whether or not you ever desired this in the first place, or has someone else decided this is the normal desire to have?*

--- Meta Nomad, [Exiting Modernity](https://jdemeta.net/2019/09/15/exiting-modernity/) // ([pdf](https://jdemeta.net/wp-content/uploads/2019/09/Exiting-Modernity.pdf))

Spending less time in front of screens (alongside some eye learning) also improves...

**Short-sightedness.**

Most cases of myopia (can't see long) are perfectly curable.

In short, too much close up weakens an eye muscle. Putting glasses in front weakens it even more, and now you need stronger glasses. You can retrain this muscle.

Check out,

- [EndMyopia](https://endmyopia.org)
- [Myopia is Mental](https://www.myopiaismental.com/)
- [Visions of Joy](https://visionsofjoy.org)

You also don't need to spend money curing...

**Baldness.**

As you can cure many cases using simple scalp massaging.

Well, according to a mate of mine who's often finding things that "sound like bullcrap but are actually true".

He recommends <https://perfecthairhealth.com>, and also...

**Mercury Detoxification.**

Which he said worked for him.

In short, you get mercury from the environment (sometimes), amalgam fillings and even in the womb, and it's a really heavy (and toxic) metal that your body can't get rid of.

You can, however, go through a 'chelation' process described in "The Mercury Detoxification Handbook" to get rid of it.

He says not everyone is affected, but it's just good to consider: especially if you're having strange health problems.

Anyway, on **intimate relationships** I'd recommend three books:

- *Models: Attract Women Through Honesty* by Mark Manson for understanding emotional vulnerability and removing neediness.
- *The Rational Male* by Rollo Tomassi, which is useful for avoiding toxic relationships.
- *The Way of The Superior Man* by David Dieda, giving a more spirital understanding of masculine, feminine and balanced energies. Pretty 'new-agey' but it's right.

and also, to send you sincere peacefulness. You've just freed yourself from a terrible disease. Look upon the world with fresh eyes and renewed meaning, and always enjoy the ride.

Welcome to the rest of your life.

Warm wishes,

[Fraser Patterson](https://fraserpatterson.au)
