# What am I giving up?

**Absolutely nothing!** Porn is difficult to give up because of the fear we’re being deprived of our pleasure or prop. The fear that certain pleasant situations will never be quite the same again. Fear you'll be left unable to cope with stressful situations. In other words, it's the effects of brainwashing deluding us into believing that sex — and by extension orgasm — is a must for all human beings. Even further, it's the belief there's something inherent in internet porn that we need, and that when we stop using we will be denying ourselves and creating a void.

Make this clear in your mind: **Porn doesn't fill a void,** ***it creates one!***

Our bodies are the most sophisticated objects on the planet. Whether you believe in intelligent design, natural selection, or a combination of both, our bodies are thousands of times more effective than man! We’re unable to create the smallest living cell or the miracles of eyesight, reproduction and various interlinked systems present in our bodies or brains. If this creator or process had intended us to handle supernormal stimulus, we’d have been provided with different reward systems. Our bodies are provided with fail-safe warning devices and we ignore these at our peril.

## There’s nothing to give up

Once you purge the little monster from your body and the brainwashing (the big monster) from your mind, you’ll neither want to masturbate often nor use internet porn for it. There are many knowns and unknowns when it comes to porn addiction, with many in the medical community having no concept of questioning or determining someone as a porn addict. A lot of reported symptoms are wrongly tagged under other causes. It’s not that users are generally stupid people, it’s just that they’re miserable without porn. Caught between the devil and the deep blue sea, abstaining and being miserable because they cannot use porn, or miserable because they’re guilty and begin despising themselves because of it. When they get symptoms such as low back pain or sexual dysfunction, their minds are torn between accepting responsibility and looking the other way.

Another smoker analogy: all of us have seen smokers who develop excuses to sneak off for a crafty puff and we see the true addiction in action. Addicts don’t do this for enjoyment, instead they do it because they’re miserable without it.

For many their first sexual experience ended in an orgasm, so they acquired the belief they can’t enjoy sex without one. For men, porn is marketed as an aid towards sex, sometimes even as an education in confidence during the act. This is nonsense, the conditioning of supernormal stimulus only succeeds in bringing it down.

Not only is there nothing to give up but massive positive gains to be had. When users contemplate quitting, they tend to concentrate on health and virility. These are valid and important reasons, but I personally believe the greatest gains are psychological:

-   The return of your confidence and courage.

-   Freedom from slavery.

-   No longer having awful black shadows at the back of your mind and despising yourself.

## Void, the void, the beautiful void!

Imagine having a cold sore on your face, so you go to the pharmacist and he gives you a free ointment to try. You put the ointment on and it disappears immediately. A week later it reappears, so you go back to the pharmacist and ask if they have any more ointment. The pharmacist says *“Sure; keep the tube, you might need it later."*

You apply the ointment and hey presto, the sore disappears once again. But every time the sore returns, it gets larger and more painful, with the interval getting shorter and shorter. Eventually, the sore covers your whole face and is excruciatingly painful, and it’s returning every half hour. You know the ointment will remove it temporarily, but you’re very worried. Will the sore eventually spread over your whole body? Will the interval disappear completely? You go to your doctor and they can’t cure it, so you try other things but nothing helps apart from the ointment.

By now you’re completely dependent on the ointment, never going out without ensuring that you have a tube with you. If you go abroad, you make sure you take several tubes with you. In addition to your worries about your health, the pharmacist is charging you a hundred dollars a tube. You have no choice but to pay up.

You stumble across an article discussing this and find out it isn’t just happening to you, many people are suffering from the same problem. In fact, the medical community has discovered that the ointment doesn’t actually cure the sore, and instead only takes it beneath the surface of the skin. It’s the ointment that caused the sore to grow, so all you have to do to get rid of the sore is to stop using the ointment and it’ll disappear in due course.

Would you continue to use the ointment? Would it take willpower to not use the ointment? If you didn’t believe the article there might be a few days of apprehension, but once you realised the sore was beginning to get better, the need or desire to use the ointment would go. Would you be miserable? Of course you wouldn’t! You had an awful problem which you thought was incurable but now you’ve found the solution. Even if it took a year for the sore to go away, each day as it improved you’d think about how marvellous you felt. This is the magic of quitting porn.

The sore isn’t the body pains, lack of normal lust, flagging arousal, fading penetration, the wasted time spent on two-dimensional images, feelings of infringement on entitlement, and despising the people who caught you or even worse, despising yourself. These are all in addition to the sore.

The sore makes us close our minds to all these things — it’s that panic feeling of wanting a fix. Non-users don’t suffer from that feeling. The worst thing we ever suffer is fear, the greatest gain being rid of that fear. It’s caused by your first session, further strengthened and caused by each subsequent one.

Some users are ‘happy’, blinded by their cunning little monsters and so go through this same nightmare, putting up phony arguments to try and justify their stupidity.

*It’s so nice to be free!*
