# Health

This is the area where the brainwashing is the greatest with users — particularly the young and single — who think they’re aware of the health risks but aren't. Many kid themselves by saying they’re prepared to accept the consequences. If your internet router had a function that played an alarm tone with a warning when you hit a porn site saying — “*Up until now you’ve gotten away with it, but if you stay another minute your head will explode.*" Would you have stayed? If you’re in doubt about the answer try walking up to a cliff, standing on the edge with your eyes closed and imagining having the choice of either quitting porn or walking up blindfolded.

There's no doubt what your choice would be, but by burying your head in the sand and hoping that you’ll wake up one morning and not want to watch porn anymore, you accomplish nothing. Users cannot allow themselves to think of the health risks, because if they do, the addiction's illusory enjoyment goes. This explains why shock treatments are so ineffective in the first stages of quitting: it's only non-users who bring themselves to read about the destructive brain changes.

Take this common conversation with users, generally younger ones.

> **Me:** “Why do you want to stop?"
>
> **User:** “*I read in a pick-up artist’s blog that it’s good to stop for four days to amp myself up.*"
>
> **Me:** “Aren't you worried about the health risks?"
>
> **User:** “*No, I could step under a bus tomorrow.*"
>
> **Me:** “But would you deliberately step under a bus?"
>
> **User:** “*Of course not.*"  
>
> **Me:** “Do you not bother to look left and right when you cross the road?"
>
> **User:** “*Of course I do.*"

Exactly, they go through a lot of trouble not to step under a bus and the odds are thousands to one against it happening. Yet the user risks the near-certainty of being crippled by their addiction and appears to be completely oblivious. Such is the power of the brainwashing; internet porn is a wolf in sheep's clothing. Isn't it strange that if we felt there were the slightest fault in an airplane we wouldn't go up in it — even though the risks are millions to one — yet we take more than a one-in-four certainty with porn and are apparently oblivious to it? What does the user get out of this? **Absolutely nothing!**

Another common myth is depression or peevishness. Many younger people aren't worried about their health because they don't suffer any of the depression or melancholy. The depression or stress isn't the disease, it's a symptom. Younger people in general don't feel the irritability or depression created due to their body's natural ability to produce more dopamine. As they age or their lives encounter serious setbacks, their already depleted resources are overworked and they’ll experience full-blown symptoms. When older users feel stressed, depressed or irritated, it's because nature's fail-safe mechanisms are protecting the nervous system from excessive dopamine-flooding through trimming receptors. The user also develops other neurological changes that keep them in the rut.

Think of it this way, if you had a nice car and allowed it to rust without doing anything about it, that would be pretty stupid. It would quickly become an immovable heap of rust, incapable of transporting you anywhere. However, it wouldn't be the end of the world as it's only a question of money. But your body is the vehicle that carries you through life. We all say that our health is our greatest asset — ask any sick millionaire. Most of us can look back on an illness or accident in our lives where we prayed to get better. By being a porn user, you’re not only letting the rust get in and doing nothing about it, you’re systematically destroying the one vehicle used to go through your entire life.

Wise up. You don't have to do this. Remember, it's doing *absolutely nothing for you*. Just for a moment, take your head out of the sand and ask yourself that if you knew with certainty that your next session would start a process that would make you utterly unresponsive to someone you deeply love, would you continue using? Speaking to the people this happens to, they certainly didn't expect it would happen to them either, and the worst thing isn't the disease itself but the knowledge that they've brought it on themselves. Try to imagine how people who've ‘hit the button’ feel, for them the brainwashing is ended. They spend the remainder of their lives thinking, “*Why did I kid myself for so long that I needed to masturbate to internet porn? If only I had the chance to go back!*"

Stop kidding yourself, you have that chance. It's a chain reaction, if you engage in the next porn session, it’ll lead you to the next one and the next. It's already happening to you. EasyPeasy promises no shock treatment so if you've already decided that you’re going to stop, the following won't be shocking for you. If you haven’t, skip the *remainder of this chapter* and come back to it once you’ve read the rest of the book.

Volumes upon volumes of research have already been written about the damage internet porn causes to our sex lives and mental well-being. The trouble is that until deciding to stop they don't want to know. Forums and mentor groups are a waste of time because porn puts the blinders on. If inadvertently read, the first thing they do is to open their favorite tube site. Porn users tend to think of the happiness, stress and sex hazards as a hit-and-miss affair, like stepping on a land mine.

Get it into your head, it's already happening. ***Every single time*** you open your porn site you’re triggering dopamine-flooding and opioids getting to work. The neural water slides are greased and the ride takes you smoothly through the next steps, your brain having already given in to the script. The nervous system is now flooded by dopamine and since it's the umpteenth time, dopamine receptors close up and the little monster uses this slight dip in pleasure compared to the last time to drive you further over the red line to more-shocking porn or behaviour in order to release more dopamine. More novelty, more dopamine and the little monster tells you to keep going. So many pictures and videos in a single session triggers a supernormal stimulus, injecting more chemicals into the brain and driving you to continue.

The entire time, your receptors are receiving information to shut down in response to the flooding. Orgasm only increases this effect and leads to withdrawal. You’re in denial since the little monster craves for its fix with no real pain and discomfort. The threat of having erectile dysfunction terrifies many, which is why they block it from their mind and overshadow it with the fear of stopping. It's not that the fear is greater, but quitting today is immediate. Why look on the negative side? Perhaps it won't happen, having bound to have quit by then anyway.

We tend to think of porn as a tug-of-war: on one side is fear, “*It’s unhealthy, filthy and enslaving.*" On the other side, the positives: “*It’s my pleasure, my friend, my crutch.*" It never seems to occur to us this side is also fear; it's not that we enjoy porn, it's that we tend to be miserable without it. Heroin addicts deprived of heroin go through misery, but picture the utter joy when they’re finally allowed to plunge a needle into their vein and end that terrible craving. Try to imagine how anyone could actually believe they get pleasure from sticking a hypodermic syringe into a vein. Non-heroin addicts don't suffer that panic feeling and heroin doesn't relieve the feeling, it causes it.

Non-users don't feel miserable if they aren't allowed to use porn — it's only users that suffer that feeling. Internet porn doesn't relieve the feeling, it causes it. The fear of the negative consequences doesn't help users quit, because they liken the feeling to walking through a minefield. If you get away with it, fine, but if you were unlucky you stepped on a mine and faced the consequences. If you knew the risks and were prepared to take them, what did it have to do with anyone else? Addicts in this state typically develop the following evasive tactics.

“***You’ll eventually get old and lose your sexual prowess anyway...***"  

Of course you do, but sexual prowess isn't the point — we’re talking slavery here. Even if that's the case, is that a logical reason for deliberately cutting yourself short?

“***Quality of life is more important than just living.***"  

  Precisely! Are you suggesting that the quality of life of an addict is greater than someone who isn't addicted? Do you really believe the quality of a user's life is better than a non-user's? A life spent covering their head in the sand and being miserable doesn't sound like a pleasant one.

“***I’m single and not planning to settle down in the future, so why not?***"

Even if that were true, is that a logical reason for playing with neurological impulse-control mechanisms? Can you possibly conceive of anyone being stupid enough to strip naked whenever they’re alone, regardless of how sure they aren't expecting anyone? **That’s what porn users effectively do!**

Progressive gunging-up of our reward circuits with excessive stimulation, and making them incapable of handling normal stresses of life doesn't help in enjoying your life with enthusiasm and vigour. Porn and masturbation has replaced the natural sexual appetite, like a chocolate bar replacing real food. Unsurprisingly, many doctors and psychologists are now relating various mental-health problems to physiological causes. The mainstream medical community has laboured that porn has never been scientifically proven to be the direct cause of the issues reported by self-confessing individuals, but admitting one's sexual inability in public is such a shame-triggering event, so why would anyone do so unless they were really concerned, having found the cause and eliminated it from their own lives?

EasyPeasy will help you rid yourself of porn and become a happy ex-user. No porn, porn-aided masturbation or unnecessary orgasms. The only aid will be the touch, sight and scent of your partner. Like wholegrain bread after a well developed appetite, you’ll no longer want the high-fructose corn syrup of internet porn. Evidence so overwhelming needs no proof; when I bang my thumb with a hammer and it hurts, it need not be proven. The stress of internet porn has flow-on effects onto other aspects of the user's life, predisposing many to turn to drugs such as cigarettes and alcohol to cope, and in some instances even turning the host to consider suicide.

Users also suffer illusions that the ill effects of porn are overstated. The reverse is the case, there's no doubt that internet porn is the major cause of sexual dysfunction and many other problems. How many divorces have been caused by porn? There are no reliable ways to know, but searches of online communities suggest the number is growing exponentially.

There's an episode of *Friends* where the guys, who were receiving continuous free porn on TV, started to wonder why the pizza delivery girl didn't ask to check out their ‘big bedroom’. When you’re addicted, you invariably project porn fantasies on real women. Imagine what careless or even accidental porn exposure on the darker sides of the internet might do to someone already at a tipping point in their life. Fighting against these porn-induced thoughts will be a major drain on their mental health.

(Here's another thought experiment: let's say someone comes to you and says they don't necessarily want an orgasm but very much want to make love, even penetratively. They want to do it for as long and as far as you can go without an orgasm — but if it happens then it’s fine. I assure you of a phenomenal new sexual experience far better than any other, if you ever get that offer. Try it.)

Effects of the brainwashing make us tend to think like the man who, having fallen off a 100-storey building, is quoted saying as he whizzes past the fiftieth floor, “*So far, so good!*" We think that as we've gotten away with it so far, one more porn session won't make the difference. See it another way: the ‘habit’ is a continuous chain for life with each session creating the need for the next. When you start the habit, you light a fuse. The trouble is, *you don’t know how long the fuse is.* Every time you give in to a porn session you’re one step closer to the bomb exploding. **HOW WILL YOU KNOW IF IT’S THE NEXT ONE?**

## Sinister Black Shadows

Users find it very difficult to believe that internet porn actually causes those insecure feelings when you’re out late at night after a contentious day at home or work. Non-users don’t suffer from that feeling, it’s porn that causes it.

Another of the great joys of quitting porn is the freedom from the sinister black shadows at the back of our minds. All users know they’re fools to close their minds from the ill effects of pornography. For most of our lives it’s automatic, but the black shadows are always lurking in our subconscious minds, just below the surface. Several of the marvellous benefits of quitting are conscious, such as the ending of the waste of time and of the sheer stupidity of making love to a two-dimensional image.

The last chapters have dealt with the considerable advantages of being a non-user, but in the interest of fairness it’s necessary to give a balanced account. Therefore, the next chapter lists the advantages of being a user.

# Advantages of Being a Porn User
