# Beware of Cutting Down

Many users resort to cutting down as a stepping-stone towards stopping, or as an attempt to control the little monster. Many recommend cutting down or a ‘porn diet’ as a pick-me-up. Using cutting down as a stepping stone to stopping is ***fatal.*** It's these attempts to cut down that keep us trapped for the remainder of our lives. Generally, cutting down follows failed attempts to stop. After a few hours or days of abstinence the user says something like:

"*I can’t face the thought of going to sleep without visiting my online harem, so from now on I’ll just use porn once in four days or purge my collection of ‘bad porn’. If I can follow this porn diet, I can either hold it there or cut down even further.*"

Certain terrible things now happen:

1.  They’re stuck with the worst of all worlds, still addicted to internet porn and keeping the monster alive not only in their body, but in their mind.

2.  Wishing their life away waiting for the next session.

3.  Prior to cutting down, whenever they wanted to visit their harem they'd fire up their browser and at least partially relieve their withdrawal pangs. Now in addition to the normal stresses of life, they’re causing themselves to suffer the withdrawal pangs for most of their lives, which makes them even more miserable and bad-tempered.

4.  Whilst indulging, they neither enjoyed most of the sessions nor realised they were using a supernormal stimulus. It was automatic, the only harem visit that was enjoyed was one after a period of abstinence. Now that they wait an extra hour for each harem visit, they ‘enjoy’ each one. The longer waited, the more ‘enjoyable' each session appears to become, because the ‘enjoyment’ in a session isn't the session itself — it's the ending of the agitation caused by the craving — whether slight physical craving or mental moping. The longer the suffering, the more ‘enjoyable’ each session becomes.

The primary difficulty in stopping isn't the neurological addiction, which is easy. Users will stop without difficulty on various occasions — the death of a loved one, family or work affairs, etc. They’ll go, say, ten days without access and it doesn't bother them. But if they went the same ten days when they could've had access to porn, they'd be tearing their hair out.

Many users will get chances during their work day and abstain, or they’ll pass through Victoria's Secret or swimming pools and so on without undue inconvenience. Many will abstain if they have to sleep on the couch temporarily to make space for a visitor, or are themselves visiting. Even in Go-Go bars or nudist beaches there have been no riots. Users are almost pleased for someone or something to say they cannot view porn. In fact, users who want to quit get a secret pleasure out of going for long periods without harem visits, giving them hope that perhaps one day they’ll never want it.

The real problem when stopping is brainwashing, an illusion of entitlement that internet porn is some sort of prop or reward and life will never be the same without it. Far from turning you off internet porn, all that cutting down accomplishes is leaving you feeling insecure and miserable, convincing you that the most precious thing on this earth is the new clip you missed, that there's no way you’ll be happy again without seeing it.

There is nothing more pathetic than the user who's been trying to cut down, suffering from the delusion that the less porn they watch, the less they'll want to visit their online harem. The reverse is true — the less they watch porn, the longer they suffer withdrawal pangs and the more they ‘enjoy' the relief of relieving them. However, they’ll notice their favourite genre isn't hitting the spot. But that won't stop them: if the tube sites were dedicated to only one star or one genre, no user would ever go more than once.

Difficult to believe? What's the worst moment of self-control one feels? Waiting for four days and then having a climax. Then, what's the most precious moment for most users on a four-day porn diet? That's right, the same climax after waiting for four days! Do you really believe that you’re masturbating to enjoy the orgasm, or the more rational explanation that you need to relieve withdrawal pangs under the illusion that you’re entitled to?

Removal of the brainwashing is essential to remove illusions about porn before you extinguish that final session. Unless you've removed the illusion that you enjoy it before you close that window, there's no way you can prove it afterwards without getting hooked again. When hovering over bookmarks and saved pictures, ask yourself where the glory in this action is. Perhaps you believe that only certain clips are of good taste, like ones on habitual or favourite themes. If so, why bother to watch other videos or themes? Because you got into the habit? Why would anyone habitually mess up their brain and waste themselves? Nothing is different after a month, so why should a porn clip be any different?

You can test this yourself. Find that hot clip from last month to prove it's different. Then, set a reminder and watch the same clip after a month without porn. It will hit (almost) the same spots as it did last month. The same clip will be different after a social event where you’re turned down or tested by a potential partner. The reason being that the addict can never be fully happy if the little monster remains unsatisfied.

Where does satisfaction come into it? It's just that they’re miserable if they can't relieve their withdrawal symptoms. The difference between watching porn and not is the difference between being happy and miserable. That's why internet porn appears to be better. Users who get on their sites first thing in the morning for porn are miserable whether watching it or not.

Cutting down not only doesn't work, but is the worst form of torture. It doesn't work because initially the user hopes that by getting into the habit less and less, they’ll reduce their desire to watch porn. It's not a habit, it's addiction. The nature of any addiction is wanting more and more, not less and less. Therefore in order to cut down, the user has to exercise willpower and discipline for the rest of their lives. So, cutting down means willpower and discipline forever. Stopping is far easier and less painful; there are literally tens of thousands of cases in which cutting down has failed.

The problem of stopping isn't the dopamine addiction, which is easy to cope with. It's the mistaken belief that porn gives you pleasure, brought about initially by brainwashing received before we started using, further reinforced by the actual addiction. All cutting down does is reinforce the fallacy further, to the extent that porn dominates their lives completely and convinces them that the most precious thing on earth is their addiction.

The handful of cases that do succeed have been achieved by a relatively short period of cutting down, followed by going ‘cold turkey’. These users stopped in spite of cutting down, not because of it. All it did was prolong the agony, failed attempts leaving users nervous wrecks and even more convinced they’re hooked for life. This is usually enough to keep them reverting back to their online harem for pleasure and crutch, or at least for another stretch before the next attempt.

However, cutting down does help to illustrate the futility of porn, clearly demonstrating that visits to the harem are not enjoyable after periods of abstinence. You have to bang your head against a brick wall (suffer withdrawal pangs) in order to make it nice upon stopping. Therefore, the choices are:

1.  Cutting down for life and suffering self-imposed torture, which you’ll be unable to do anyway.

2.  Increasingly torturing yourself for life, which is pointless.

3.  Being nice to yourself, and cutting porn out altogether.

The other aspect that cutting down demonstrates is that there's no such thing as the odd or occasional harem visit. Internet porn is a chain reaction that will last the rest of your life unless you make a positive effort to break it.

**Remember: Cutting down will drag you down.**
