# Just One Peek

"Just one peek" is a myth that you must remove from your mind:

-   It's *just one peek* that gets us started in the first place.

-   It's *just one peek* to tide us over a difficult patch or on a special occasion that defeats most of our attempts to stop.

-   It's *just one peek* that after having succeeded in breaking the addiction, sends us back into the trap. Sometimes it's just to confirm they don't need porn anymore and one harem visit does just that.

The aftereffects of porn will be horrible and convince the user they’ll never become hooked again — but they already are. The user feels that something making them so miserable and guilty shouldn't have made them do it, yet it did.

It's the thought of ‘one special session’ that often prevents users from stopping, the one after your long conference trip, hard day at work, fight with the kids, or incident where your partner rejects you for sex. Get it ***firmly*** in your mind that there's no such thing as ‘just one peek’. It's a chain reaction that will last the rest of your life unless broken. The myth about the odd, special occasion keeps users moping after stopping. Get into the habit of never seeing the ‘no big deal’ session, it's fantasy. Whenever you think about porn, see a filthy lifetime of spending eons behind a screen for the privilege of destroying yourself mentally and physically — a lifetime of slavery and hopelessness. It isn't a crime if your erections are unreliable, but it is when you could be happier long-term but instead choose to sacrifice that for short term ‘pleasure’.

It's okay we can't always come up with ‘something to do’ for the void; doing that isn't realistically possible in every instance for our entire lives. We can plan for most of them, but sometimes it just happens. Good and bad times also happen, irrespective of porn. But get it clearly into your mind, the porn isn't it. You’re stuck with either a lifetime of misery or none at all. You wouldn't dream of taking cyanide just because you liked the taste of almonds, so stop punishing yourself with the occasional ‘no-big-deal’ session. Ask a user with issues, "*If you had the opportunity to go back to the time before you became hooked, would you have become a user?*" The answer is inevitably, "*You’ve got to be joking!*" Yet every user has that choice every day of their lives, so why don't they opt for it? The answer is fear, the fear that they can't stop or that life won't be the same without it.

Stop kidding yourself! You can do it, anybody can. It's ridiculously easy but in order to make it so, there are certain fundamentals to get clear in your mind.

1.  There's nothing to give up, only marvellous positive gains to achieve.

2.  Never convince yourself of the odd ‘no-big-deal’ or ‘just-one-peek’ session. It doesn't exist. There's only a lifetime of filth and slavery.

3.  There's nothing different about you; any user can find it easy to stop.

Many users believe that they’re confirmed addicts or have addictive personalities. This usually happens as a result of reading excessive amounts of shocking neuroscience. There's no such thing, nobody is born with the need to masturbate to video clips before they became hooked. It's the drug that hooks you, not the nature of your character or personality. The nature of addictive supernormal stimulus makes you believe this is the case. However, it's essential to remove this belief because if you believe you’re addicted, you will be, even after the little monster in your body is long dead. It's essential to remove all of this brainwashing.
