# Casual Users

Heavy users tend to envy the casual porn user. We've all met these characters: "*Oh, I can go all week without a session, it doesn’t really bother me.*" We wish we were like that. This might be hard to believe, but no user enjoys being a user. Never forget:  


|   *No user ever decided to become one, casual or otherwise, **therefore,** *

|       *All users feel stupid, **therefore,** *

|         *All users have to lie to themselves and others in a vain attempt to justify their stupidity.*


Golf fanatics brag about how often they play and want to play, so why do users brag about how little they masturbate? If that's the true criterion, then surely the accolade is not masturbating at all, isn't it?

If someone said to you, "*I can go all week without carrots and it doesn't bother me in the slightest*", you'd think you were talking to a nutcase. If I enjoyed carrots, why would I want to go all week without them? If I didn't enjoy them, why would I make such a statement? So when a user makes a comment about surviving a week without a session, they’re trying to convince themselves — and you — that they don't have a problem. But there would be no need to make a statement if they didn't have a problem. Translated, this comment is "*I managed to survive a whole week without porn.*" Like every user, hoping that after this they could survive the rest of their lives. If only able to survive a week, can you imagine how precious the session must have been afterwards, having felt deprived for an entire week?

This is why casual users are effectively more hooked than heavy users. Not only is the illusion of pleasure greater, but they have less incentive to quit because they spend less time on it and are therefore less vulnerable to health risks. Occasionally, they may experience sexual dysfunction, but are unsure what caused it and so it's blamed on other factors. Remember, the only pleasure users get is in the search-and-seek dopamine cycle and relieving the withdrawal pangs, as has already been explained. The pleasure is an illusion — imagine the little porn monster as a near-imperceptible itch that we remain unaware of most of the time.

If you have a permanent itch, the natural tendency is scratching it. As reward circuits become increasingly immune to dopamine and opioids, the natural tendency is to edge, escalate, binge, novelty-seek, shock-seek, etc. There are four main factors that prevent users from chain-viewing.

**Time.**
Most cannot afford to.

**Health.**
In order to relieve the itch, we have to consume all free material that's available and then some. Capacity to cope with that kind of binging varies with each individual, and at different times and different situations in their lives. This acts as an automatic restraint.

**Discipline.**
Discipline is imposed by society, by the user's work, friends and relatives, or perhaps even by the user themselves as a result of the natural tug-of-war going on in every user's mind.

**Imagination.**
Lack of imagination plays down the shock, novelty, and other values of the clip on a subjective basis.

It's easy to think of ‘non-casual’ users as weak, unable to understand why others are able to limit their ‘intake’. However, heavy users should keep in mind that most casual users are simply incapable of chain-viewing, which requires very strong imagination and stamina. Some of these once-a-week users that heavy users tend to envy are physically incapable of doing more, or because their job, society, or own hatred of becoming hooked won't allow them to.

It may be advantageous to provide a few definitions.

**The Non-user**

Someone who has never fallen prey to the trap but shouldn't be complacent. They’re a non-user only by luck or grace of goodness. All users were convinced they'd never become hooked and some non-users keep trying an occasional session.

**The Casual User**

Of which there are two basic classifications:

1.  The user who's fallen for the trap but doesn't realise it – don't envy such users. They’re merely sampling the nectar at the mouth of the pitcher plant and in all probability will soon be heavy users. Remember, just as all alcoholics started off as casual drinkers, so too do all users start off casually.

2.  The user who was previously a heavy user, and so thinks they can't stop. These users are the saddest of all and they fall into various categories, each requiring separate comment.

**The Once-A-Day User**

If they enjoy their entitlement to orgasm, why use internet porn only once daily? If they can take it or leave it, why bother at all? Remember, the ‘habit’ is — in actuality — banging your head against a wall to make it relaxing upon stopping. The once-a-day user relieves their withdrawal pangs for less than an hour each day. Although unaware, the rest of their day is spent banging their head against this wall, doing so for most of their lives. They’re using once a day because they cannot risk getting caught, or messing with their neurological health. It's easy to convince the heavy user they don't enjoy it, but significantly harder to convince a casual one. Anyone who has gone through an attempt to cut down will know it's the worst torture of all, and almost guaranteed to keep you addicted for the rest of your life.

**The Rejected User**

They demand the right to orgasm every day, but their sex partner isn't always happy to fulfill the request. Initially, they're using internet porn to fill this void, but upon taking the exciting ‘water slide’ they’re trapped in a cycle of novelty, shock, supernormal images, etc. In fact, they’re happy with their partner's rejection as it provides something of an excuse. If internet porn gives so much to you, why bother to have a partner at all? Set them free instead. They’re not even enjoying sessions when they have to ‘carry’ their partner in their mind. At some point, they’re looking for their real-life partner to hand them an excuse to venture into the dark valleys of the internet.

**The Porn-Diet User**

Also known as, "*I can stop whenever I want to. I’ve done it thousands of times!*"

If they think dieting helps getting them into the mood to pick up partners, why are they even on the diet of once in every four days? Nobody can predict the future, and what if the happenstance of meeting occurred an hour after your scheduled session? Also, if occasional ‘cleaning the plumbing’ is good to relieve tension, why not plumb every day? It's been proven that masturbation isn't required to keep genitals healthy and internet porn isn't required at all. Even if that's the case, no pick-up-artist ‘guru’ who has read about the neurological damage will ever recommend watching super-stimulus porn. The truth is, the porn-diet user is still hooked. Although they’re rid of the physical addiction, they’re still left with the primary problem of brainwashing. They’re hoping each time they’ll stop for good, but soon fall for the same trap again.

Most users actually envy these stoppers-and-starters and think about how ‘lucky’ the dieter is to be able to control their usage. However, they overlook the fact that the dieter isn't controlling their usage — when they’re using, they wish they weren't. They go through the hassle of stopping, then begin to feel deprived and fall for the trap again, wishing they hadn't. They get the worst of both worlds. If you think about it, this is true in the lives of users when allowed to have a session — taking it as entitled or wishing they didn't. It's only when deprived that porn becomes precious. The ‘forbidden-fruit’ syndrome is one of the awful dilemmas for users. They can never win because they’re moping for a myth, an illusion. There's only a single way they can win, stopping moping by stopping porn!

**The "I Only Watch Static/Tame/Home-Made Porn" User**

Yes, everyone does this to start with, but isn't it amazing how the average shock-value of the clips seems to rapidly increase, and before we know it we’re feeling deprived (tolerance)? The novelty lacks with static porn, so we pay the piper for a cup of grease and ride down the water slide towards resentment and guilt. The worst thing you can do is use your partner's pictures (with approval, of course) for masturbation. Why? Because in the process you’re re-wiring your brain for the seeking-, searching- and variety-induced dopamine flushes. Chemically, the porn water slides in the brain is DeltaFosB building up, so you’ll find yourself having difficulties when you’re with them in real time.

Another trap in this category is ‘amateur’ and ‘home-made’ porn. Most are fakes and you know it, plus you’re also not going to stop at the very first one that hits your eyes, instead continuing to seek and search. Remember, it's not only orgasm the brain seeks, but the novelty of the hunt that gives the water slide its thrill. The porn content isn't the issue — whether amateur or professional — it's the flushes of dopamine in the brain causing build-up of tolerance and satiation. Porn destroys normal brain operation, masturbation confusing the muscle–brain response; orgasm floods the brain with opioids and makes the pathway easier to follow next time.

**The "I’ve Stopped But Have an Occasional Peek" User**

In a way, peeking users are the most pathetic of all. Either they go through their lives believing they’re being deprived, or more often, the occasional peek becomes two, sliding downwards on the slippery slope, sooner or later falling back to being heavy users. They've again fallen for the very trap they fell into in the first place.

There are two other categories of casual users. The first is the type masturbating to images or clips of the latest celebrity sex tapes hitting the news, or something that they ‘carried home’ from their ‘accidental’ viewing at school or work. These people are really just non-users, but they feel that they’re missing out. They want to be part of the action, with most of us starting off this way. Next time, notice that after a while the celebrity of your fantasy isn't doing it for you anymore. The more ‘unattainable’ the target of your fantasy, the more frustrating the withdrawal of the orgasm is.

The second category has been gaining attention recently, best described by outlining a case shared online.

A professional woman had been reading internet porn stories for many years and had never used more or less than once each night. Incidentally, she was a very strong-willed lady. Most users would wonder why she wanted to stop in the first place — gladly pointing out that there was no risk of PIED, or PE in her case (untrue). She wasn't even using static images, the stories being far tamer than any material that they themselves use on a daily basis.

They make the mistake of assuming that casual users are happier and more in control. They might be more in control, but they certainly aren't happy. In the woman's case, she wasn't satisfied with her partner nor with real sex, and highly irritable when responding to her daily stresses and strains. Her nearest-and-dearest was unable to figure out what was bothering her. Even if she convinced herself to be unafraid of her usage through rationalisation, she still found herself unable to enjoy real relationships which invariably involve ups and downs. Her brain's reward centre was unable to make use of normal destressors present in life as a result of daily dopamine flooding. Subsequent downregulation of her brain's receptors had rendered her melancholic under most circumstances. Like most, she had a great fear of pornography's dark side and treatment of women – before her first time. Eventually, she fell victim to societal brainwashing and tried her first site. Unlike most who capitulate and become chain users, upon seeing the foul clips of violence, she resisted the slide.

All you ever enjoy in porn is ending the craving that started before it, whether the almost-imperceptible physical craving, or the mental torture of not being allowed to scratch the itch. Internet porn itself is poison, which is why you only suffer the illusion of enjoying it after periods of abstinence. Similarly to hunger or thirst, the longer you suffer it, the greater the pleasure when finally relieved. Making the mistake of believing porn is just habit, they think: "*If I can keep it down to a certain level or only on special occasions, my brain and body will accept it. Then, I can keep using at that level or reduce it further should I wish to.*"

Get it clear in your mind, the ‘habit’ doesn't exist. Porn is drug addiction, with the natural tendency being to relieve withdrawal pangs, not enduring them. To hold it at the level you’re currently at would require you to exercise tremendous amounts of discipline and willpower for the rest of your life. As your brain's reward centre becomes tolerant of dopamine and opioids, it wants more and more, not less and less.

As porn begins to gradually destroy your nervous system, courage, confidence and impulse controls, you become increasingly unable to resist reducing the interval between each session. This is why, in the early days, we can take it or leave it. If we get a sign of something amiss mentally or physically, we just stop. Don't envy this woman — when you watch only once every twenty-four hours it appears to be the most precious thing on earth, turning porn into a ‘forbidden fruit’. For many years this poor woman had been at the centre of a tug-of-war.

Though unable to stop using, she was frightened to escalate to streaming clips. For twenty-three hours and ten minutes of every one of those days she had to fight the temptation and lack of feelings towards her boyfriend. It took tremendous willpower to do what she did, eventually reducing her to tears. Such cases are rare, but look at it logically: either there's a genuine crutch or pleasure in porn, or there isn't. If there is, who wants to wait an hour, a day, or even a week? Why should you be deprived of the crutch or pleasure in the meantime? If there's no genuine crutch or pleasure, why bother paying a visit to your online harem?

Here is another case of a once-in-four-days man, describing his life as follows:

> "*I’m forty years old, I’ve suffered PIED (porn-induced erectile dysfunction) with real women and even when using porn, which is most of the time. It's been a while since I had a full erection. Before going on the once-in-four porn diet, I used to sleep soundly through the night after my session. Now I wake up every hour of the night and it's all I can think about. Even when asleep, I dream about my favorite clips. On days after my scheduled session I feel pretty down, the diet taking up all of my energy. My SO would leave me alone because I’m so bad-tempered and if she can’t leave, she won’t have me in the house. I go for jogs outside but my mind is obsessed with it.*
>
> "*On the scheduled day I begin planning earlier in the night, getting very irritated if something happens against my plans. I'd back out of conversations and give in (only to later regret) at work and home. I’m not an argumentative guy, but I don't want the topic or conversation to hold me down. I remember occasions when I'd pick silly fights with my SO. I wait for ten o’clock and when it arrives my hands are shaking uncontrollably. I don't start the deed right away — as there are new videos that have been added — and ‘shop around’. My mind tells me that since I've starved myself for four days I deserve a ‘special’ clip that has to be worth the time spent searching. Eventually I settle for one or two, but want it to last so that I can ‘survive’ through the next four days, so I take more time to finish the deed.*"  

In addition to his other troubles, this poor man has no idea that he's treating himself to poison. First, he's suffering ‘forbidden-fruit syndrome’ and then forcing his brain to flush dopamine. Comparatively, his dopamine receptors aren't as cut down, but he's greasing the porn water slides, seeking, searching for edging, novelty, variety, shock and anxiety in order to survive the next four days. You probably picture this man as a pathetic imbecile, but this isn't so. As a former athlete and marine sergeant, he didn't want to become addicted to anything. However, upon returning from war he trained as an IT technician in a veterans' rehab program. 

When entering the civil workforce, he was a well paid IT professional in a bank, and was given a laptop to take home. It was the year that famous socialites ‘leaked’ their porn videos online and there was much talk about it. He then got hooked, spending the rest of his life paying through the nose and ruining himself physically and mentally. If he were an animal, society would have long since put him out of his misery, yet we still allow mentally and physically healthy young teenagers to become hooked. You may think this case and notes are exaggerated, but this case — while extreme — is far from unique. There are tens of thousands of similar stories. Can you be sure that none of his friends and acquaintances envied him for being a once-in-four man? If you think this couldn't happen to you, **stop kidding yourself.**

**IT'S ALREADY HAPPENING.**

Like other addicts, porn users are notorious liars, even to themselves. They have to be. Most casual users indulge far more times and on far more occasions than they’ll admit to. Many conversations with so called ‘twice-a-week' users will admit they've done it more than three or four times that week. Read reddit, NoFap and rebooting-forum stories from casual users, and you’ll find they’re either counting days or waiting to fail. You don't need to envy casual users, and you don't need to use either, life is infinitely sweeter without it. Take the following log:

"*It started with a simple challenge to not touch my junk for a day and being unable. I don’t think about masturbation anymore, it doesn’t cross my mind. That is possible, I promise you. The riches that await those who are able – they’re incredible.*"

Teenagers are generally more difficult to cure, not because they find it more difficult to stop, but because they don't believe they’re hooked or are at the initial stages of the trap, generally suffering from the delusion that they’ll automatically have stopped before the second stage.

Parents of children who loathe internet porn shouldn't have a false sense of security. All children loathe the dark sides of porn before becoming hooked. At one point, you did too. Don't be fooled by scare campaigns either, the trap is the same as it always was. Children know that internet porn is supernormal stimulus, but they also know that one ‘visit’ or ‘peek’ won't do it. At some stage they may be influenced by a partner, classmate, or work colleague.

Please do not become complacent in this matter. Society's failure to prevent adolescents from becoming addicted to internet porn and other drugs is perhaps the most disturbing facet of this addiction. Adolescent brains are significantly more plastic, and it is necessary to educate and protect them. If you're unsure where to start, good resources include the YourBrainOnPorn.com book to educate yourself on the neuroscience. Even if you suspect your teenager might be already hooked, the book provides foundational understanding in helping someone to escape. Otherwise, recommend this book!
