# The YouTube / Twitch / Instagram User

This user should be grouped with casual users, but the effects are so insidious that it merits a separate chapter. It leads to the breakdown of self-control, nearly causing a split for one NoFap forum user:

> *“I was three weeks into one of my failed attempts to stop, the attempt had been triggered by my wife's worry about my unreliable hard-ons and lack of interest. I had told her that it wasn't her, just job pressure. She said, "I know you've handled the work pressure before, but how would you feel if you were me and had to watch someone you love systematically destroying themselves?" It was an argument I found irresistible, hence the attempt to stop. She knows I'm not cheating, but this is in a way worse than that. The attempt ended after three weeks, culminating in a heated argument an old friend. It didn't register until years after that my devious mind had deliberately triggered off the argument, I felt justifiably aggravated at the time but don't believe it was coincidence as I had never argued with this particular friend before, nor have I since. It was clearly the little monster at work.*
>
> *“Regardless, I had my excuse. I desperately needed a release and it didn't matter how. My wife wasn't in the mood so I had feelings of ‘entitlement', so I convinced myself it would be okay if I ‘restricted' myself by avoiding porn sites and staying this side of the ‘red line' by only watching YouTube videos. But my wife ended up ‘coming around' as the night unfolded and wanted to make love, however I was tired and without my ‘horsepower' so invented a headache. I couldn't bear to think of the disappointment this would cause my wife. Then I gradually returned to old ways, with YouTube becoming my new harem destination. I remember being quite pleased at the time, thinking that it was at least cutting my consumption. Eventually, she accused me of continuing to ignore her in bed. I hadn't realised it, but she described the times I'd caused an argument and stormed out of the house. At other times, taking two hours to purchase some minor item and faking sprains. I'd made feeble excuses to cop out of wooing her so when I have a reliable online harem it's even harder."*

The worst thing about the YouTube user is that it supports the fallacy in their mind that they're being deprived. Simultaneously, it causes major losses of self-respect; an otherwise honest person may force themselves to deceive their loved one. It probably has happened, or is still happening to you in some form.

Problems faced with websites like Twitch, Instagram, TikTok, Twitter (and most social media) are primarily driven by supplementation. Driven by novelty-seeking dopamine urges, they trick themselves into believing they're on a safe site. Remember — the thrill is in seeking, not killing, and the little monster doesn't care where its fix comes from. For the user, the ‘soft' content received in their various online feeds gives them fleeting relief of withdrawal pangs, keeping them hooked and waiting for their next session.

The model in the image/video is indeed beautiful, and if you had them on your side right now they could surely give you pleasure, but that image can't... It simply just isn't real. Your brain is tricked like a bull running into a red cape, and afterwards doesn't understand why it did it. One could think that you could just look at those images then, without masturbating. But remember that your brain is hooked on the limitless novelty, and the little monster doesn't care where its fix comes from. It's the same trap.

You might have watched the TV series *Columbo*. The theme of each episode is similar. The villain, usually a wealthy and respected businessman, has committed what he's convinced is the perfect murder and his confidence in his crime remaining undetected receives a boost when he discovers the rather shabby and unimpressive-looking Detective Columbo is in charge of the case.

Columbo has this frustrating practice of closing the door after finishing his interrogation, having assured the suspect that he's in the clear. But just before the satisfied look has disappeared from the murderer's face, Columbo reappears, saying "*Just one small point, sir, which I'm sure you can explain...*" The suspect stammers, and from that point on he knows that Columbo will gradually wear him down. No matter how heinous the crime, from that point on sympathies were with the murderer.

These bouts are similar, the tension of not being allowed to cross the red line to get the porn fix they ‘rightly deserved', then wondering where the pleasure was after finishing the deed. Fear of crossing the line, losing control and returning to the bed, only to be stalked by the fear your partner wanted sex. The ‘safe' YouTube videos will no longer satisfy you due to desensitisation, lack of novelty, and the certain knowledge that sooner or later you'll visit your favorite online harem. The final humiliation and shame then being when that certainty become a fact, followed by the immediate return to chain-viewing.

**OH, THE JOYS OF BEING A PMOer!**
