# A social habit?

Health of the mind and body are the primary reasons for we *should* want to stop — but then, they always have been. We don't actually need scientific research and knowledge in neuroscience to tell us porn is addictive and can potentially shatter our lives. These bodies of ours are the most sophisticated objects on the planet, and any user knows from the first session that the stimulus can go to excess and turn poisonous.

The only reason why we ever get involved with porn is the cycle's overlap with our evolutionary programming. Internet porn is highly available, free and streaming twenty-four hours a day. Porn was once considered harmless, but that was when the images were static and the videos involved a trip to the local store for a VHS tape.

Today, it's generally considered — even by users themselves — that porn is a supernormal stimulus and addiction-forming. In the old days, the strong man didn't admit that he masturbated, with jerk being a derogatory term. In every pub, club or bar, the majority of men would be proudly wanting to take a woman home and have real sex. Today, the position is completely reversed for the internet porn addict. Today's man realises that he's beginning to feel he doesn't need a woman. Banding together online, he discusses experiences, devises strategies and explores options. Today's strong man doesn't want to depend on drugs. Through social revolution, all users are giving serious thought to stopping internet porn and masturbation. Today's users consider porn a useless and harmful activity.

The most significant trend noticed on forums is the increasing emphasis on the anti-social aspects of porn, the days when a man boasted of having sex and orgasms every day is slowly being replaced with realisation of slavery to the porn monster.

The only reason why people continue after being educated is because they've failed to stop or are too frightened to try. There's a wide spectrum of interest in the subject, some abstaining from porn, masturbation and orgasm — with or without partners. Practices that separate the tantric and propagative parts of sex such as semen retention and Karezza are discussed and adopted in droves. Many aforementioned failures are in reality fall-forwards, thus somewhat benefiting people practising them. Once you start the no-PMO route you'll find the best fit that applies to your life; it's encouraged to devise your own plan on orgasms after understanding and practising sexual separation. Whatever your route, you'll see value in limiting the number of times you flush your brain with chemicals through orgasm, and never again seeing porn, sex and orgasm as a pleasure or crutch for your emotional self.

Various popular online communities founded by non-users are dedicated to quitting not only porn but also masturbation. These sites are ultimately beneficial to those escaping, but most notes point them to try willpower. The consequence of obsession with abstinence streaks and other measures is self-pity and lack of elation. Much of the brainwashing remains alive and well. Eventually, someone breaks down and a domino effect takes place, other users finding out they aren't the only ones. However, their efforts aren't in vain, they're falling forward, albeit with lots of self-torturing as they shut down their browsers but not the desire and need. EasyPeasy works in the reverse, shutting down the need and desire first, before shutting down the browser. Every day more and more users leave the sinking ship and those left on it become terrified they'll be the last.

**DON'T LET IT BE YOU!**
