# Avoid False Incentives

Many users on the willpower method attempt to increase their motivation through construction of false incentives. There are many examples of this, a typical one being to reward themselves with gifts after not watching porn for a month. This appears to be a logical and sensible approach but is in fact false, because any self-respecting user would rather continue watching porn every day than reward themselves with a self-given gift. This generates doubt in the user's mind, because not only will they have to abstain for *thirty days*, they're not sure they'll even *enjoy* the days without porn. Their only pleasure or crutch has been taken away! All this does is increase the size of the sacrifice the user feels they're making, now ever more precious in their mind.

Other examples include:

-   I'll stop so that it'll force me to get a social life and more real sex.

-   I'll stop so that some magical energy will help me to leap above the competitors and get the partner I pursue.

-   I'll stop so that I can commit myself to not wasting my energy and enthusiasm with porn in order to grow hunger in myself.

These are true, can be effective, and you might end up getting what you want — but think on it for a second. If you do get what you wanted, once the novelty has gone you'll feel deprived; if you didn't, you'll feel miserable. Either way, sooner or later you will fall for the same trap again.

Linking quitting to a false incentive only increases doubt, because if you don't get your incentive (and even if you do) you'll begin thinking doubtful thoughts like “*Will quitting actually make my life better? If I quit and don't get what I want, did I use the method correctly?*" Thoughts like these increase feelings of sacrifice and therefore create pangs.

Another typical example is online or forum pacts. These have the advantage of eliminating temptation for certain periods. However, they generally fail for the following reasons:

1.  The incentive is false. Why would you want to stop just because other people are doing so? All this achieves is generating additional pressure and increases the feeling of sacrifice. It's fine if all users genuinely want to stop at one particular time — but you can't force them to stop, although all secretly want to. Until they're ready to do so, a pact creates additional pressure, which only increases their desire to watch. This turns them into secret viewers, further increasing the feeling of dependency.

2.  Dependency on each other using the willpower method breeds feelings of undergoing a period of penance, during which they wait for the urge to disappear. If they give in, there's a sense of failure. When using the willpower method at least one of the participants is bound to give up, providing the other participants with the excuse they've been waiting for. It's not their fault, they would have held out but ‘Fred' let them down. The truth is that most of them have already been cheating.

3.  Sharing the credit is the reverse of dependency. There's a marvellous sense of achievement in stopping porn and when doing it alone, the acclaim you receive from your friends and online buddies can be a tremendous boost over the first few days. However, when everybody is doing it at the same time, the credit has to be shared and the boost is consequently reduced.

4.  Another classic example is the guru promise. Stopping will give you happiness because you're no longer engaged in the tug-of-war, your brain beginning rewiring and regaining impulse control. However, you must keep in mind this will neither make you a sex god nor win you the lottery. Nobody except you cares in the slightest if you stop porn. You aren't a weak person if you're using porn three times a day and have PIED, or a strong person if you're an addict and don't.

Stop kidding yourself. If the job offer of ten months' work for twelve months' salary a year, or the risks of cutting down your brain's ability to cope with day-to-day stress and strains, or putting yourself at odds with having a reliable erection, or the lifetime of mental and physical torture and slavery didn't stop them, the above few phoney incentives won't make the slightest bit of difference, and will only succeed in making the sacrifice appear worse. Instead, concentrate on the other side:

\"What am I getting out of it? Why do I need to watch porn?\"

Keep looking at the other side of the tug of war and ask yourself what porn is doing for you. *ABSOLUTELY NOTHING.* Why do I need to do it? *YOU DON'T! YOU'RE ONLY PUNISHING YOURSELF.* It's Pascal's Wager: you have almost nothing to lose (fading arousal), chances of big profits (full and reliable arousal, mental well being and happiness) and no chance of losing big.

Why not then declare your quitting to friends and family? Well, it'll make you a proud ex-addict or ex-user, not an elated and happy non-user. It might scare your partner a bit since they may see this as an scheme to have more sex, in a sort of New Age way. They may also fear you turning into a sex machine. It's hard to explain unless they're open-minded.

Any attempt to get others to help you in quitting gives more power to the little monster. Pushing it from your mind and totally ignoring it has the effect of trying *not* to think of it. Be mindful instead, as soon as you spot the thoughts, cues (home alone) or absent-minded thoughts, just say to yourself *\"Great, I'm no longer a slave to porn. I'm free and happy to know differences in sex!\"* This will cut the oxygen to the thought and stop it from burning towards urges and cravings. In this aspect, practising mindfulness meditation can be helpful to assist in the depersonalisation of thoughts.
