# The Easy Way To Stop

This chapter contains instructions regarding the easy way to stop porn. Providing you follow the instructions, you'll find that stopping ranges from relatively easy to enjoyable! Provided you follow the instructions below it's ridiculously easy to stop porn. All you have to do is two things:

1.  Make the decision that you are never going to watch porn again.

2.  Don't mope about it. Rejoice.

You're probably asking, *“Why the need for the rest of the book? Why couldn't you have said that in the first place?*" Well, the answer is that you'd have eventually moped about it and consequently eventually changed your decision. You've probably already done that many times before.

As already said, porn is a subtle, sinister trap. The main problem of stopping isn't the dopamine addiction — which is certainly a problem, but not the primary one — it's the brainwashing. Therefore, it's necessary to destroy all of the myths and delusions first. Understand your enemy, know their tactics, and you'll easily defeat them. Having spent large chunks of my life suffering black depression while attempting to quit, upon finally escaping, I went straight to zero without a bad moment. It was enjoyable even through the withdrawal period and I've never had the slightest pang since. On the contrary, it was one of the most wonderful things that's happened in my life.

My final attempt was different. Like all users nowadays, the problem had been given serious thought in my mind. Up to then, after failing, it was routine to console myself with the thought that it would be easier next time. It had never occurred to me that I'd have to go on this way for the rest of my life. That thought filled me with horror and I began thinking very deeply about the subject.

Rather than firing up the browser subconsciously, I instead analysed my feelings and confirmed what I already knew. I wasn't enjoying porn and found it filthy and disgusting. I started looking at non-users living in other parts of the world, or older people who never got to know the tube sites. Up until then, I'd always regarded non-users as wishy-washy, unsociable, finicky people. However, examining them when they appeared, they appeared to be — if anything — stronger and more relaxed. They appeared to be able to cope with the stresses and strains of life and seemed to enjoy social functions more than porn users. They certainly had more sparkle and zest than them.

I started talking to ex-users. Up to that point, I'd always regarded them as being forced to give up for health or religious reasons and were always secretly longing for a harem visit. A few did say, *“You get the odd pangs, but they're so few and far between they aren't worth bothering about."* Most instead said, *“Miss it? You must be joking! Life's never felt better!"* Even failures were fall-forwards for them — they didn't condemn themselves and unconditionally accepted instead. Like a coach who'll accept a mistake by a genuinely golden player. Talking to ex-users destroyed another myth I'd always had in my mind, that there was an inherent weakness within me, until it dawned on me that all go through this private nightmare.

Basically, I said to myself, *“Scores of people are stopping now and leading perfectly happy lives, I didn't need to do it before I started and I can remember having to work hard to get used to this filth. So why do I need to do it now?"* In any event, I didn't enjoy porn, hating the entire filthy ritual and didn't want to spend the rest of my life in slavery to this disgusting addiction. I then said this to myself:

*“Whether you like it or not, you've completed your last session."*

I knew, right from that point that I'd never have another session again. I wasn't expecting it to be easy, just the reverse. I fully believed that I'd signed up for months of black depression and spending the rest of my life having the occasional pang. Instead, it has been absolute bliss right from the start.

It took me a long time to work out why it had been so easy and why I hadn't suffered those terrifying withdrawal pangs. The reason is that they don't exist, it's the doubt and uncertainty that creates pangs. The beautiful truth is that ***it's easy to stop porn.*** It's only indecision and moping that makes it difficult. Even while addicted, users can go for relatively long periods at certain times without it. It's only when you want it, but can't have it, that you suffer.

Therefore, the key to making it easy is to make stopping certain and final. Not hoping, but *knowing* you've kicked it, having made the decision. Never doubt or question it, in fact, just the reverse — always rejoicing! If you can be certain from the start, it'll be easy. But how can you be certain from the start? That's why the rest of the book is necessary. There are certain essential points necessary to get clear in your mind before you start:

1.  Realise you can achieve it. There's nothing different about you and the only person who can make you watch is yourself. Not that star, never in their wildest dreams having thought about themselves being used for reducing virility.

2.  There's absolutely nothing to give up. On the contrary, there's enormous positive gains to be made. Not only that you'll be healthier and richer, but you'll enjoy the good times more and be less miserable during the bad.

3.  There's no such thing as a peek or a single visit. Pornography is drug addiction and a chain reaction, by moaning about the odd visit you'll only be needlessly punishing yourself.

4.  See porn not as a ‘boys-will-be-boys' habit that might injure you, but as drug addiction. Face up to the fact that whether you like it or not, **you've got the disease.** It won't go away because you bury your head in the sand. Remember that like all crippling diseases, it not only lasts for life but gets exponentially worse. The easiest time to cure it is now.

5.  Separate the disease — the neurological addiction — from the mindset of being a user or not. All users, if given the opportunity to go back to the time before they became hooked, would jump at the opportunity. You have that opportunity today! Don't even think about it as ‘giving up'.

Upon making the final decision that you've had your last visit, you'll already be a non-user. A user is one of those poor wretches going through life destroying themselves with porn. A non-user is someone who doesn't. Once you've made that final decision, you've already achieved your objective. Rejoice in the fact, don't sit around moping and waiting for the chemical addiction to go. Get out and enjoy life immediately. Life is marvellous even when you're addicted and each day will get so much better when you aren't.

The key to making it easy to quit is to be certain that you'll succeed in abstaining completely during the withdrawal period, a maximum of three weeks. If you're in the correct frame of mind, you'll find this ridiculously easy.

By this stage, if you've opened your mind as requested at the beginning, you'll have already decided you're going to escape. You should now have feelings of excitement, like a dog straining at the leash, unable to wait to break down the DeltaFosB porn water slides. If you have a feeling of doom and gloom, it'll be for one of the following reasons:

1.  Something hasn't gelled in your mind. Re-read the above five points and ask yourself if you believe them to be true. If you doubt any point, re-read the appropriate sections of the book.

2.  You fear failure itself. Don't worry, just read on and you'll succeed. The whole business of internet porn is a confidence trick of a gigantic scale. Intelligent people fall for confidence tricks, but only a fool, once having found out about the trick, goes on kidding themselves.

3.  You agree with everything but are still miserable. Don't be! Open your eyes, something marvellous is happening. You're about to escape from the prison, it's essential to start with the correct frame of mind: *“It's marvellous that I'm a non-user!"*

All that needs to be done now is keeping you in that frame of mind during the withdrawal period, and the next few chapters deal with specific points to enable you to do so. After the withdrawal period you won't have to think that way, you'll think it automatically. The only mystery in your life will be why you didn't see it before. However, two important warnings.

-   Delay your plan to make your last visit until you've finished the book.

-   A withdrawal period of up to three weeks has been mentioned many times, which can cause misunderstanding. First, you may subconsciously feel you have to suffer for three weeks. You don't. Secondly, avoid the trap of thinking *“Somehow I've got to abstain for three weeks and then I'll be fine."* Nothing magical will actually happen after three weeks, you won't suddenly feel like a non-user, as they don't actually feel any different from users. If you're moping about stopping during the three weeks, in all probability you'll still be moping about it after the three weeks. Summarised, if you can start right now by saying *“I'm never going to use again, isn't it marvellous?"*, after three weeks all temptation will go. Whereas if you say, *“If only I can survive these three weeks without porn …"*, you'll be dying for a harem visit after the three weeks are up.

Think of it this way — your brain wants to maintain the status quo, so if you're under the belief that you're losing something good when quitting, you'll obviously feel horrible. It's impossible to force yourself to feel a certain way if your brain doesn't believe it. This is why it's important to go through the trouble of removing the illusion that pornography gives you anything at all. That's how you know you're sacrificing nothing.

Sexual dysfunction has a lot to do with your brain and mind frame. Internet porn rewires your brain's reward circuit and gives your mind a ‘doubting' mindset. This self-doubt will undoubtedly cause sexual dysfunction. Having all the desire in your upper part, but putting up with no arousal in your lower is the worst thing to happen to your mindset. Libido going hand in hand with romance is the elixir of youth that you can have until you die. You'll keep the probabilities high by quitting, but that isn't the only or major gain. It's your freedom from slavery!
