# Will it be harder for me?

There are infinite combinations of factors determining how easily each individual user will quit. To start with, each of us has our own character, career, personal circumstances, timing, metabolism, etc. Certain professions may make it harder than others, but providing the brainwashing is removed, this doesn't have to be so. Take the following few examples.

Occasionally, it is difficult for members of the medical profession. We think it should be easier for doctors because they're more aware of the effects, but although this supplies more forceful reasons for stopping, it doesn't make it any easier to accomplish. The reasons are as follows:

1.  The constant awareness of the health risks creates fear, one of the conditions under which we feel the need to relieve withdrawal pangs.

2.  A doctor's work is exceedingly stressful and they're usually unable to relieve the additional stress of withdrawal pangs while working.

3.  They have the additional stress of guilt, feeling that they should be setting an example for the rest of the population. This puts more pressure on them and increases the feeling of deprivation.

After a hard day at work when their stress is momentarily relieved by porn, that session becomes incorrectly attached to the relief experienced. Because of this misassociation of ideas, porn gets credit for the whole situation, suddenly becoming very precious upon quitting and going through withdrawal pangs. This is a form of casual user and applies to any situation where the user is forced to abstain for lengthy periods. Under the willpower method, the user is miserable because they're being deprived and not enjoying the tiredness and sleep that comes after a session. Their sense of loss is greatly increased. However, if you can first remove the brainwashing and moping regarding porn, the break and sleep can still be enjoyed even while the body is craving the amine transmitters — serotonin, norepinephrine and dopamine.

Another difficult situation is boredom, particularly when combined with periods of stress. Typical examples are students and single parents, work being stressful yet monotonous. During an attempt to stop on the willpower method, the single person has long periods in which to mope about their ‘loss', which in turn increases feelings of depression. Again, this can be easily overcome if your frame of mind is correct. Don't worry that you're continually reminded that you've stopped porn. Use such moments to rejoice in the fact you're ridding yourself of the evil monster.

If you have a positive frame of mind these pangs will become moments of pleasure. Remember, any user, regardless of age, sex, intelligence or profession can find it easy and enjoyable to stop provided **you follow all the instructions.**

## Primary Reasons for Failure

There are two primary reasons for failure. The first being the influence of external stimuli — a commercial, online news article, internet browsing, etc. They find themselves in a weak moment, or even become jealous when seeing intimacy in social scenarios. This topic has already been discussed at length. Use the moment to remind yourself there's no such thing as one visit or peek. Rejoice in the fact that you've broken the chain of mental slavery. Remember that the user envies you and you should feel pity for them, for they need it.

The other reason is having a bad day. Get it clear in your mind before you start, that whether you're a user or not you will have good and bad days. It rains for both the pope and the murderer. Life is relative and you can't have ups without downs. The issue with the willpower method is that as soon as the user has a bad day, they begin moping for a visit to the ‘harem', which further compounds the issue. The non-user is better equipped to handle stresses and strains, not only physically but mentally. If you have a bad day during the withdrawal period just take it on the chin; remind yourself that bad days existed when you were addicted, otherwise you wouldn't have decided to stop. Instead of moping about it, recognise it instead: *“Okay, so today's not so good but porn won't cure it. Tomorrow will be better and at least I've got a marvellous bonus, I've kicked that awful addiction."*

When you're a porn user, you have to block your mind to porn's negatives. Users never have brain fog, they're just ‘a bit down'. When you're having life's inevitable troubles and you experience a thought of wanting porn, are you happy and cheerful? Of course you aren't. Once you stop, the tendency is blaming everything that goes wrong on the fact you've stopped.

If work stresses you out, you think, “*At times like this I would've had a session.*" This is true, but the important thing that's forgotten is that porn didn't solve the problem, and you're simply punishing yourself by moping for illusory crutches. You're creating an impossible situation, miserable because you can't masturbate to porn, yet you'll be even more miserable if you do. *You know that you've made the correct decision by stopping it, so why punish yourself by doubting your decision?*

Remember, a positive mental approach is essential — always.
